<?php

/**
 * @file
 * Module for the dialogue import.
 */
include_once 'pw_dialogues.features.inc';

/**
 * A buffer of overlap between the imports in seconds.
 */
define('PW_DIALOGUES_INTERVAL', 86400); // one day buffer

/**
 * Implements hook_menu().
 */
function pw_dialogues_menu() {
  $items['dialogues/%taxonomy_term'] = [
    'title callback' => 'pw_dialogues_page_title',
    'title arguments' => [1],
    'page callback' => 'pw_dialogues_page',
    'page arguments' => [1],
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];
  $items['dialogues/%taxonomy_term/%'] = [
    'title callback' => 'pw_dialogues_page_title',
    'title arguments' => [1, 2],
    'page arguments' => [1, 2],
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];
  $items['admin/config/pw/dialogues/settings'] = [
    'title' => 'Dialogue importer',
    'description' => 'Configure the source URL for the dialogue importer.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pw_dialogues_admin_settings_form'),
    'access arguments' => array('import dialogue_importer feeds'),
    'file' => 'pw_dialogues.admin.inc',
  ];
  $items['admin/config/pw/dialogues'] = [
    'title' => 'Dialogue importer',
    'description' => 'Mass re-import dialogues.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pw_dialogues_admin_reimport'),
    'access arguments' => array('import dialogue_importer feeds'),
    'file' => 'pw_dialogues.admin.inc',
  ];
  $items['api/import/dialogue/%'] = [
    'title' => 'imports dialogue',
    'access arguments' => array('access content'),
    'page callback' => 'pw_dialogues_triggered_import',
    'type' => MENU_SUGGESTED_ITEM,
  ];
  return $items;
}

/**
 * Implements hook_block_info().
 */
function pw_dialogues_block_info() {
  $blocks['profile'] = [
    'info' => t('Questions and answers'),
    'cache' => DRUPAL_NO_CACHE,
  ];
  $blocks['recent'] = [
    'info' => t('Recent questions and answers (in parliament)'),
    'cache' => DRUPAL_NO_CACHE,
  ];
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function pw_dialogues_block_view($delta) {
  switch ($delta) {
    case 'profile':
      return pw_dialogues_profile_block();
    case 'recent':
      return pw_dialogues_recent_block();
  }
}

/**
 * Implements hook_cron().
 *
 * Imports all dialogues once at night. Normally all dialogues should be
 * already imported by push request to api/import/dialogue/% via the moderation
 * backend.
 */
function pw_dialogues_cron() {

  // get import base url
  if ($source = variable_get('pw_dialogues_importer_source')) {

    // append the updated_since GET parameter to the source URL.
    if ($last_import = variable_get('pw_dialogues_importer_last_import', 0)) {

      // import only every X days / hours/ etc
      if ($last_import < time() - PW_DIALOGUES_INTERVAL) {

        // import buffer: 1.5 of import interval
        $updated_since_timestamp = $last_import - PW_DIALOGUES_INTERVAL * 1.5;
        $updated_since = date('Y-m-d\\TH:i:s', $updated_since_timestamp);
        if (strpos($source, '?') === FALSE) {
          $source .= '?updated_since=' . $updated_since;
        }
        else {
          $source .= '&updated_since=' . $updated_since;
        }

        // do the import
        pw_dialogues_do_import_questions($source);
        pw_dialogues_do_import_answers($source);

        // trigger userarchive cron which
        if (function_exists('pw_userarchives_cron')) {

          // query which politicians have a changed question and answer count.
          $users = db_query('SELECT DISTINCT f.field_dialogue_recipient_target_id
            FROM {field_data_field_dialogue_recipient} AS f
            INNER JOIN {feeds_item} AS i ON f.entity_type = i.entity_type AND f.entity_id = i.entity_id
            WHERE i.imported >= :imported', array(':imported' => $updated_since_timestamp))->fetchCol();

          // rewrite user archive cache table
          foreach ($users as $uid) {
            pw_userarchives_cron($uid);
          }
        }

        // save last import date
        variable_set('pw_dialogues_importer_last_import', REQUEST_TIME);
      }
    }
  }
}

/**
 * Implements hook_node_view().
 */
function pw_dialogues_node_view($node, $view_mode) {
  if ($node->type != 'dialogue') {
    return;
  }

  $recipient = pw_dialogues_recipient_user_revision($node);
  $node->content['user_display_name'] = _pw_get_fullname($recipient);
  $node->content['user_picture'] = field_view_field('user', $recipient, 'field_user_picture', ['label' => 'hidden', 'settings' => ['image_style' => 'square_small']]);
  $node->content['user_party'] = field_view_field('user', $recipient, 'field_user_party', ['label' => 'hidden', 'type' => 'taxonomy_term_reference_plain']);
  $node->content['user_url'] = url(entity_uri('user', $recipient)['path']);

  $comments = pw_dialogues_answers($node);

  if ($comments) {
    if ($view_mode == 'full') {
      $node->content['answers'] = comment_view_multiple($comments, $node, $view_mode);
    }
    else {
      $node->content['answers'] = comment_view_multiple(array_slice($comments, 0, 1, TRUE), $node, $view_mode);
    }
  }

  if (node_is_page($node)) {
    $parliament_tid = $node->field_parliament[LANGUAGE_NONE][0]['tid'];
    if ($node->field_dialogue_before_election[LANGUAGE_NONE][0]['value']) {
      menu_tree_set_path('main-menu', "profiles/$parliament_tid/candidates");
    }
    else {
      menu_tree_set_path('main-menu', "profiles/$parliament_tid/deputies");
    }
  }
}

/**
 * Implements hook_entity_presave().
 *
 * Modifies data on dialogue save (or import via api).
 */
function pw_dialogues_entity_presave($entity, $type) {

  // Force URL alias for dialogues
  if ($type == 'node' && $entity->type == 'dialogue' && isset($entity->nid)) {
    module_load_include('inc', 'pathauto');
    $entity->path['pathauto'] = TRUE;
    $alias_action = variable_get('pathauto_update_action', 0);
    variable_set('pathauto_update_action', PATHAUTO_UPDATE_ACTION_DELETE);
    $entity->path = pathauto_node_update_alias($entity, 'update');
    variable_set('pathauto_update_action', $alias_action);
  }
}

/**
 * Implements hook_webform_submission_insert().
 */
function pw_dialogues_webform_submission_insert($node, $submission) {
  if ($submission->nid == 10446 && variable_get('pw_modtool_api_queue_run', FALSE)){ // node id of question form
    $queue = DrupalQueue::get('pw_dialogues_questions', TRUE);
    $payload = array(
      'type' => "question",
      'recipient_id_e' => TRUE,
      'recipient_id' => $submission->data[18][0],
      'text' => $submission->data[25][0],
      'topic' => $submission->data[12][0],
      'summary' => null,
      'context' => $submission->data[19][0],
      'sender_first_name' => $submission->data[8][0],
      'sender_last_name' => $submission->data[9][0],
      'sender_email' => $submission->data[7][0],
      'sender_city' => $submission->data[10][0],
      'sender_ip' => $submission->remote_addr,
      'inserted_date' => date('Y-m-d\TH:i:s', $submission->submitted)
    );
    $queue->createItem($payload);
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function pw_dialogues_cron_queue_info() {
  if (variable_get('pw_modtool_api_queue_run', FALSE)) {
    $queues['pw_dialogues_questions'] = array(
      'worker callback' => '_pw_dialogues_questions_queue_worker',
      'time' => variable_get('pw_modtool_api_queue_run_time', 60),
      'skip on cron' => variable_get('pw_modtool_api_skip_on_cron', TRUE)
    );
  }
  return $queues;
}

/**
 * Implements worker callback
 * Throws exception upon unsuccessful delivery
 */
function _pw_dialogues_questions_queue_worker($payload) {
  $payload['auth_token'] = variable_get('pw_modtool_api_auth_token');
  $endpoint = variable_get('pw_modtool_api_question_endpoint');
  $basic_auth = variable_get('pw_modtool_api_basic_auth', FALSE);
  $curl = curl_init($endpoint);
  curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($payload));
  curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
  if ($basic_auth){
    curl_setopt($curl, CURLOPT_USERPWD, $basic_auth);
  }
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
  $response = curl_exec($curl);
  $response_info = curl_getinfo($curl);
  curl_close($curl);
  if ($response_info['http_code'] != 200) {
    throw new Exception('Modtool API responded with a return code of ' . $response_info['http_code'] . '. The response body is: ' . $response);
  }
}

/**
 * Implements hook_feeds_presave().
 */
function pw_dialogues_feeds_presave(FeedsSource $source, $entity, $item) {

  if ($source->id == 'dialogue_importer' || $source->id == 'dialogue_message_importer') {

    // delete and skip item instead of importing
    if (!$entity->status) {

      // skip item
      $entity->feeds_item->skip = TRUE;

      // delete dialogue node (question)
      if ($entity->nid && !isset($entity->cid)) {
        entity_delete("node", $entity->nid);
      }

      // delete dialogue comments (answers)
      elseif ($entity->cid) {
        entity_delete("comment", $entity->cid);
      }
    }

    // remove empty attachments
    elseif (isset($entity->field_dialogue_documents['und'][0]['url']) && empty($entity->field_dialogue_documents['und'][0]['url'])) {
      $entity->field_dialogue_documents = NULL;
    }
    else {

      // add title to link
      foreach ($entity->field_dialogue_documents['und'] as &$document) {
        $document['title'] = basename($document['url']);
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function pw_dialogues_theme() {
  return [
    'dialogues_stats' => [
      'variables' => [
        'questions' => NULL,
        'answers' => NULL,
        'answer_ratio' => NULL,
        'answer_ratio_by_party' => NULL,
        'average_response_time' => NULL,
        'before_election' => NULL,
      ],
      'template' => 'dialogues-stats',
    ],
  ];
}

/**
 * Implements hook_query_TAG_alter().
 */
function pw_dialogues_query_ignore_standard_replies_alter(QueryAlterableInterface $query) {
  $query->join('field_data_field_dialogue_is_standard_reply', 's', 'c.cid = s.entity_id');
  $query->condition('s.field_dialogue_is_standard_reply_value', 0);
}

/**
 * Title callback: Sets the title for the dialogues page.
 */
function pw_dialogues_page_title($parliament_term, $uid = NULL) {
  if (!isset($uid)) {
    return t('Questions to deputies in @parliament', ['@parliament' => $parliament_term->name]);
  }
  else {
    return t('Questions to @name', ['@name' => _pw_get_fullname(user_load($uid))]);
  }
}

/**
 * Page callback: Displays questions and answers for the given parliament.
 */
function pw_dialogues_page($parliament_term, $uid = NULL) {
  $limit = 12;
  $q = search_api_query('node_index');
  $q->condition('type', 'dialogue');
  $q->condition('field_parliament', $parliament_term->tid);

  if (isset($uid)) {
    $q->condition('field_dialogue_recipient', $uid);
  }

  if (isset(drupal_get_query_parameters()['keywords'])) {
    $f = $q->createFilter('OR');
    $f->condition('body:value', drupal_get_query_parameters()['keywords']);
    $f->condition('comments:field_dialogue_comment_body:value', drupal_get_query_parameters()['keywords']);
    $q->filter($f);
  }

  $response = $q
    ->sort('created', 'DESC')
    ->range(pager_find_page() * $limit, $limit)
    ->execute();

  if ($response['result count'] > 0) {
    pager_default_initialize($response['result count'], $limit);
    $build = node_view_multiple(node_load_multiple(array_keys($response['results'])), 'tile');
    $build['#theme_wrappers'] = ['container__tiles'];
    $build['nodes']['#modifier'] = 'qa';
    $build['pager'] = [
      '#theme' => 'pager',
      '#weight' => 5,
    ];
  }
  else {
    $build = [
      '#markup' => t('Sorry, there are no results matching your query.'),
    ];
  }

  return $build;
}

/**
 * Page callback: Imports questions.
 */
function pw_dialogues_triggered_import() {
  drupal_add_http_header('Content-type', 'text/plain; charset=utf8');
  $debug_message = array();
  $debug_message['request_uri'] = request_uri();
  $return_value = 'FAILED';
  if (is_numeric(arg(3))) {

    // prepare for import
    $dialogue_id = arg(3);
    $source = variable_get('pw_dialogues_importer_source');
    $source .= $dialogue_id;
    $source .= '?unreleased=1';
    $debug_message['source'] = $source;

    // retrieve what to do (delete, create, ...)
    $doc = new DOMDocument();
    $doc->preserveWhiteSpace = false;
    $doc->load($source);
    $xpath = new DOMXpath($doc);
    $xlist_status = $xpath->query("//message[type='question']/status");
    $xnode_status = $xlist_status->item(0)->nodeValue;

    // do import
    pw_dialogues_do_import_questions($source);

    // check if dialogue was imported
    $efq_nodes = new EntityFieldQuery();
    $efq_nodes->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'dialogue')
      ->fieldCondition('field_dialogue_id', 'value', $dialogue_id);
    $result = $efq_nodes->execute();
    $debug_message['result'] = $result;

    // dialogue found
    if (isset($result['node'])) {
      $dialogue_nid = key($result['node']);
      $node = node_load($dialogue_nid);
      $recipient_id = $node->field_dialogue_recipient['und'][0]['target_id'];

      // delete answers and re-import them
      /* $sql = "SELECT cid FROM {comment} WHERE nid=:nid";
        $cids_to_delete = db_query($sql, array(':nid' => $dialogue_nid))->fetchCol();
        $debug_message['cids_to_delete'] = $cids_to_delete;
        comment_delete_multiple($cids_to_delete); */
      pw_dialogues_do_import_answers($source);

      // set return_value to OK
      if (is_numeric($recipient_id) && ($user = user_load($recipient_id)) || $node->status != 1) {
        $return_value = 'OK';
        if (function_exists('pw_userarchives_cron')) {
          pw_userarchives_cron($recipient_id);
        }
      }
    }

    // node deleted
    elseif ($xnode_status != 1 && !isset($result['node'])) {
      $return_value = 'OK';
    }
  }

  _pw_send_debug_mail('Import ' . $return_value . ': ' . request_uri(), $debug_message);
  print $return_value;
}

/**
 * Displays the questions and answers section of a profile.
 *
 * @return array
 *   The block render array.
 */
function pw_dialogues_profile_block() {
  $block = [];

  if (menu_get_item()['page_callback'] == 'user_revision_show') {
    $map = menu_get_item()['original_map'];
    $account = user_revision_load($map[1], $map[3]);
  }
  else {
    $account = menu_get_object('user');
  }

  if (!$account || !_pw_user_has_role($account, 'Politician')) {
    return $block;
  }

  $block['subject'] = t('Questions and Answers');
  $result = pw_dialogues_by_user_revision_query($account)->propertyOrderBy('created', 'DESC')->execute();

  if (!empty($result['node'])) {
    $nodes = node_load_multiple(array_keys($result['node']));
    $inline_js = 'window.dialogues = ' . drupal_json_encode(pw_dialogues_topics_by_user_revision($account));
    $block['content'] = node_view_multiple(array_slice($nodes, 0, 12, TRUE), 'embedded');
    $block['content']['nodes']['#theme_wrappers'] = ['container__swiper'];
    $block['content']['stats'] = [
      '#theme' => 'dialogues_stats',
      '#questions' => $account->number_of_questions,
      '#answers' => $account->number_of_answers,
      '#answer_ratio' => round(100 * $account->number_of_answers / $account->number_of_questions, 0),
      '#average_response_time' => round(pw_dialogues_average_response_time_by_account($account) / 86400),
    ];
    $block['content']['stats']['#attached']['js'][$inline_js] = [
      'scope' => 'footer',
      'type' => 'inline',
    ];
    $block['overview_url'] = url('dialogues/' . pw_profiles_parliament($account)->tid . '/' . $account->uid);
  }
  $block['content']['question_form'] = node_view(node_load(10446), 'form');

  return $block;
}

/**
 * Displays the questions and answers section of a profile.
 *
 * @return array
 *   The block render array.
 */
function pw_dialogues_recent_block() {
  $block = [
    'subject' => t('Questions and answers'),
  ];
  $term = menu_get_object('taxonomy_term', 2);

  if (!$term || $term->vocabulary_machine_name != 'parliaments') {
    return $block;
  }

  $result = pw_dialogues_by_parliament_query($term)
    ->propertyOrderBy('created', 'DESC')
    ->range(0, 4)
    ->execute();

  if (!empty($result['node'])) {
    $today = new DateTime();
    $election_date = new DateTime($term->field_parliament_election[LANGUAGE_NONE][0]['value'], new DateTimeZone($term->field_parliament_election[LANGUAGE_NONE][0]['timezone']));
    $before_election = ($today < $election_date) ? 1 : 0;

    $nodes = node_load_multiple(array_keys($result['node']));
    $inline_js = 'window.dialogues = ' . drupal_json_encode(pw_dialogues_topics_by_parliament($term)) . ';';
    $questions = pw_dialogues_by_parliament_query($term)->count()->execute();
    $answers = pw_dialogues_answered_questions_by_parliament($term);
    $block['content'] = node_view_multiple($nodes, 'tile');
    $block['content']['stats'] = [
      '#theme' => 'dialogues_stats',
      '#questions' => $questions,
      '#answers' => $answers,
      '#answer_ratio' => round(100 * $answers / $questions, 0),
      '#answer_ratio_by_party' => pw_dialogues_party_ratios_by_parliament($term),
      '#average_response_time' => round(pw_dialogues_average_response_time_by_parliament($term) / 86400),
      '#before_election' => $before_election,
      '#weight' => -5,
    ];
    $block['content']['stats']['#attached']['js'][$inline_js] = [
      'scope' => 'footer',
      'type' => 'inline',
    ];
  }

  return $block;
}

/**
 * Import dialogues (questions) from the given source.
 *
 * @param string $source
 *   The URL of the mod-tool.
 *
 * @return boolean
 */
function pw_dialogues_do_import_questions($source) {
  $dialogue_feed = feeds_source('dialogue_importer');
  $dialogue_feed->addConfig(array(
    'FeedsHTTPFetcher' => array(
      'source' => $source,
    ),
  ));
  while (FEEDS_BATCH_COMPLETE != $dialogue_feed->import()) {
    ;
  }

  watchdog('dialogue_importer', 'questions imported from @source', ['@source' => $source]);

  return TRUE;
}

/**
 * Imports answers from the given source.
 *
 * In order to avoid checking the answers for spam the user is switched to
 * the site administrator account for the duration of the import. See @link
 * https://www.drupal.org/docs/7/security/safely-impersonating-another-user.
 *
 * @param string $source
 *   The URL of the mod-tool.
 *
 * @return boolean
 */
function pw_dialogues_do_import_answers($source) {
  $original_user = $GLOBALS['user'];
  $old_state = drupal_save_session();
  drupal_save_session(FALSE);
  $GLOBALS['user'] = user_load(1);

  $message_feed = feeds_source('dialogue_message_importer');
  $message_feed->addConfig(array(
    'FeedsHTTPFetcher' => array(
      'source' => $source,
    ),
  ));
  while (FEEDS_BATCH_COMPLETE != $message_feed->import()) {
    ;
  }

  $GLOBALS['user'] = $original_user;
  drupal_save_session($old_state);

  watchdog('dialogue_message_importer', 'answers imported from @source', ['@source' => $source]);

  return TRUE;
}

/**
 * Returns query for all questions received by the given account version.
 *
 * @param object $account
 *   The user account (version).
 *
 * @return EntityFieldQuery
 *   The query object.
 */
function pw_dialogues_by_user_revision_query($account) {
  $q = new EntityFieldQuery();
  $q->entityCondition('entity_type', 'node');
  $q->entityCondition('bundle', 'dialogue');
  $q->propertyCondition('status', NODE_PUBLISHED);
  $q->fieldCondition('field_dialogue_recipient', 'target_id', $account->uid);
  $q->fieldCondition('field_parliament', 'tid', pw_profiles_parliament($account)->tid);
  $q->fieldCondition('field_dialogue_before_election', 'value', _pw_user_has_role($account, 'Candidate'));

  return $q;
}

/**
 * Returns query for all questions to politicians in the given parliament.
 *
 * @param object $term
 *   The parliament term.
 *
 * @return EntityFieldQuery
 *   The query object.
 */
function pw_dialogues_by_parliament_query($term) {
  $today = new DateTime();
  $election_date = new DateTime($term->field_parliament_election[LANGUAGE_NONE][0]['value'], new DateTimeZone($term->field_parliament_election[LANGUAGE_NONE][0]['timezone']));

  $q = new EntityFieldQuery();
  $q->entityCondition('entity_type', 'node');
  $q->entityCondition('bundle', 'dialogue');
  $q->propertyCondition('status', NODE_PUBLISHED);
  $q->fieldCondition('field_parliament', 'tid', $term->tid);
  $q->fieldCondition('field_dialogue_before_election', 'value', ($today < $election_date) ? 1 : 0);

  return $q;
}

/**
 * Returns the answers to the given question.
 *
 * @param object $node
 *   The dialogue node.
 *
 * @return array
 *   The answers.
 */
function pw_dialogues_answers($node) {
  $q = new EntityFieldQuery();
  $q->entityCondition('entity_type', 'comment');
  $q->propertyCondition('status', COMMENT_PUBLISHED);
  $q->propertyCondition('nid', $node->nid);
  $q->propertyOrderBy('created');
  $q->addTag('node_access');
  $q->addTag('comment_filter');

  $result = $q->execute();

  if (!empty($result['comment'])) {
    return comment_load_multiple(array_keys($result['comment']));
  }
}

/**
 * Returns a query object with common joins and conditions added.
 *
 * @param object $parliament_term
 *   The parliament term.
 * @param bool $before_election
 *   Whether dialogues before or after the election should be included.
 *
 * @return SelectQuery
 *   The query object.
 */
function pw_dialogues_aggregate_base_query($parliament_term, $before_election) {
  $q = db_select('node', 'n');
  $q->join('field_data_field_parliament', 'p', 'n.nid = p.entity_id');
  $q->join('field_data_field_dialogue_before_election', 'e', 'n.nid = e.entity_id');
  $q->condition('n.type', 'dialogue');
  $q->condition('n.status', NODE_PUBLISHED);
  $q->condition('p.field_parliament_tid', $parliament_term->tid);
  $q->condition('e.field_dialogue_before_election_value', $before_election);

  return $q;
}

/**
 * Returns the average response time in seconds for the given user.
 *
 * @param object $account
 *   The user account.
 *
 * @return int
 *   The average response time in seconds.
 */
function pw_dialogues_average_response_time_by_account($account) {
  $parliament_term = pw_profiles_parliament($account);
  $before_election = _pw_user_has_role($account, 'Candidate') ? 1 : 0;

  $q = pw_dialogues_aggregate_base_query($parliament_term, $before_election);
  $q->join('comment', 'c', 'n.nid = c.nid');
  $q->condition('c.uid', $account->uid);
  $q->addTag('ignore_standard_replies');
  $q->addExpression('AVG(c.created - n.created)');

  return $q->execute()->fetchField();
}

/**
 * Returns the average response time in seconds for the given parliament.
 *
 * @param object $term
 *   The parliament term.
 *
 * @return int
 *   The average response time in seconds.
 */
function pw_dialogues_average_response_time_by_parliament($term) {
  $today = new DateTime();
  $election_date = new DateTime($term->field_parliament_election[LANGUAGE_NONE][0]['value'], new DateTimeZone($term->field_parliament_election[LANGUAGE_NONE][0]['timezone']));
  $before_election = ($today < $election_date) ? 1 : 0;

  $q = pw_dialogues_aggregate_base_query($term, $before_election);
  $q->join('comment', 'c', 'n.nid = c.nid');
  $q->addTag('ignore_standard_replies');
  $q->addExpression('AVG(c.created - n.created)');

  return $q->execute()->fetchField();
}

/**
 * Returns the number of answered questions for the given parliament.
 *
 * @param object $term
 *   The parliament term.
 *
 * @return int
 *   The number of answered questions.
 */
function pw_dialogues_answered_questions_by_parliament($term) {
  $today = new DateTime();
  $election_date = new DateTime($term->field_parliament_election[LANGUAGE_NONE][0]['value'], new DateTimeZone($term->field_parliament_election[LANGUAGE_NONE][0]['timezone']));
  $before_election = ($today < $election_date) ? 1 : 0;

  $q = pw_dialogues_aggregate_base_query($term, $before_election);
  $q->join('comment', 'c', 'n.nid = c.nid');
  $q->addTag('ignore_standard_replies');
  $q->addExpression('COUNT(DISTINCT n.nid)');

  return $q->execute()->fetchField();
}

/**
 * Returns number of questions by topic for the given user.
 *
 * @param type $account
 *   The account object.
 *
 * @return array
 *   An associative array with topics as key and numbers as values.
 */
function pw_dialogues_topics_by_user_revision($account) {
  $parliament_term = pw_profiles_parliament($account);
  $before_election = _pw_user_has_role($account, 'Candidate') ? 1 : 0;

  $q = pw_dialogues_aggregate_base_query($parliament_term, $before_election);
  $q->join('field_data_field_dialogue_recipient', 'r', 'n.nid = r.entity_id');
  $q->join('field_data_field_dialogue_topic', 't', 'n.nid = t.entity_id');
  $q->join('taxonomy_term_data', 'td', 't.field_dialogue_topic_tid = td.tid');
  $q->addField('td', 'name');
  $q->addExpression('COUNT(n.nid)', 'count');
  $q->condition('r.field_dialogue_recipient_target_id', $account->uid);
  $q->condition('t.entity_type', 'node');
  $q->groupBy('t.field_dialogue_topic_tid');

  return $q->execute()->fetchAllKeyed();
}

/**
 * Returns number of questions by topic for the given parliament.
 *
 * @param object $term
 *   The parliament term.
 *
 * @return array
 *   An associative array with topics as key and numbers as values.
 */
function pw_dialogues_topics_by_parliament($term) {
  $today = new DateTime();
  $election_date = new DateTime($term->field_parliament_election[LANGUAGE_NONE][0]['value'], new DateTimeZone($term->field_parliament_election[LANGUAGE_NONE][0]['timezone']));
  $before_election = ($today < $election_date) ? 1 : 0;

  $q = pw_dialogues_aggregate_base_query($term, $before_election);
  $q->join('field_data_field_dialogue_topic', 't', 'n.nid = t.entity_id');
  $q->join('taxonomy_term_data', 'td', 't.field_dialogue_topic_tid = td.tid');
  $q->addField('td', 'name');
  $q->addExpression('COUNT(n.nid)', 'count');
  $q->condition('t.entity_type', 'node');
  $q->groupBy('t.field_dialogue_topic_tid');

  return $q->execute()->fetchAllKeyed();
}

/**
 * Returns answer ratios by party for the given parliament term.
 *
 * @param object $term
 *   The parliament term.
 */
function pw_dialogues_party_ratios_by_parliament($term) {

  $party_ratios = [
    'in_previous_parliament' => [],
    'not_in_previous_parliament' => []
  ];

  $today = new DateTime();
  $election_date = new DateTime($term->field_parliament_election[LANGUAGE_NONE][0]['value'], new DateTimeZone($term->field_parliament_election[LANGUAGE_NONE][0]['timezone']));
  $before_election = ($today < $election_date) ? 1 : 0;

  $parties_in_previous_parliament = [];
  if ($before_election && $field_previous_parliament = field_get_items('taxonomy_term', $term, 'field_parliament_previous')){
    $previous_parliament = taxonomy_term_load($field_previous_parliament[0]['tid']);
    if ($previous_parliament){
      $q = db_select('user_archive_cache', 'uac');
      $q->join('field_revision_field_user_party', 'f_party', "uac.vid = f_party.revision_id AND f_party.entity_type = 'user'");
      $q->fields('f_party', ['field_user_party_tid']);
      _pw_uac_add_conditions($q, array(
        'parliament' => $previous_parliament->name,
        'roles' => 'deputy',
        'date' => date('Y-m-d'),
      ));
      $q->groupBy('f_party.field_user_party_tid');
      $parties_in_previous_parliament = $q->execute()->fetchCol();
    }
  }

  $q = db_select('user_archive_cache', 'uac');
  $q->addExpression('COUNT(*)', 'count_politicians');
  $q->addExpression('SUM(number_of_questions)', 'count_questions');
  $q->addExpression('SUM(number_of_answers)', 'count_answers');
  $q->addExpression('SUM(number_of_answers) / SUM(number_of_questions) * 100', 'percentage');
  $q->join('field_revision_field_user_party', 'f_party', "uac.vid = f_party.revision_id AND f_party.entity_type = 'user'");
  $q->join('taxonomy_term_data', 't_data', 'f_party.field_user_party_tid = t_data.tid');
  $q->addField('t_data', 'name', 'party');
  $q->addExpression(
    sizeof($parties_in_previous_parliament) > 0
      ? format_string('t_data.tid IN (@party_tids)', ['@party_tids' => implode(',', $parties_in_previous_parliament)])
      : '1',
    'is_top_party');
  $q->orderBy('is_top_party', 'DESC');
  $q->orderBy('percentage', 'DESC');
  $q->orderBy('count_politicians', 'DESC');
  $q->orderBy('party', 'ASC');
  $q->groupBy('t_data.tid');
  _pw_uac_add_conditions($q, array(
    'parliament' => $term->name,
    'roles' => $before_election ? 'candidate' : 'deputy',
    'date' => date('Y-m-d'),
  ));
  $result = $q->execute();

  foreach ($result as $row) {
    if ($row->is_top_party == '1') {
      $party_ratios['in_previous_parliament'][$row->party] = $row;
    }
    else {
      $party_ratios['not_in_previous_parliament'][$row->party] = $row;
    }
  }

  return $party_ratios;
}

/**
 * Returns the account version of the recipient of the question.
 *
 * @param object $node
 *   The dialogue node.
 *
 * @return object
 *   The account version.
 */
function pw_dialogues_recipient_user_revision($node) {
  $recipient = NULL;
  $uid = $node->field_dialogue_recipient[LANGUAGE_NONE][0]['target_id'];
  $before_election = $node->field_dialogue_before_election[LANGUAGE_NONE][0]['value'];

  $result = db_select('user_archive_cache', 'uac')
    ->fields('uac', ['uid', 'vid'])
    ->condition('uid', $uid)
    ->condition('parliament_name', pw_globals_parliament($node)->name)
    ->condition('user_role', $before_election ? 'candidate' : 'deputy')
    ->execute()
    ->fetchAssoc();

  if (!empty($result)) {
    $recipient = user_revision_load($result['uid'], $result['vid']);
  }

  return $recipient;
}

/**
 * Returns array representation of dialogue for serialization.
 *
 * @param object $node
 *   The dialogue node.
 *
 * @return array
 *   The array representation.
 */
function pw_dialogues_to_array($node) {
  if (!empty($node->field_dialogue_topic[LANGUAGE_NONE])) {
    $topic = taxonomy_term_load($node->field_dialogue_topic[LANGUAGE_NONE][0]['tid']);
  }
  $data = [
    'id' => $node->nid,
    'topic' => isset($topic) ? $topic->name : NULL,
  ];
  return $data;
}
