<?php
/**
 * @file
 * Code for the PW Blog feature.
 */

include_once 'pw_blog.features.inc';

/**
 * Implements hook_menu().
 */
function pw_blog_menu() {
  $items = [];
  $items['blog'] = [
    'title' => 'Blog',
    'page callback' => 'pw_blog_page',
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];

  return $items;
}

/**
 * Implements hook_blockreference_blocks_pre_alter().
 */
function pw_blog_blockreference_blocks_pre_alter(&$blocks, $context) {
  if ($context['entity']->type == 'blogpost') {
    $allowed_block_ids = array('webform:client-block-104846');
    foreach ($blocks as $id => $block) {
      if (!in_array($id, $allowed_block_ids)) {
        unset($blocks[$id]);
      }
    }
  }
}

/**
 * Implements hook_block_info().
 */
function pw_blog_block_info() {
  $blocks['related_blogposts'] = [
    'info' => t('Related blog posts'),
    'cache' => DRUPAL_NO_CACHE,
  ];
  $blocks['recent_blogposts'] = [
    'info' => t('Recent blog posts'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  ];
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function pw_blog_block_view($delta = '') {
  switch ($delta) {
    case 'related_blogposts':
      return pw_blog_related_blogposts_block();
    case 'recent_blogposts':
      return pw_blog_recent_blogposts_block();
    default:
      return [];
  }
}

/**
 * Page callback: Displays a listing of blog posts.
 */
function pw_blog_page() {
  $build = [];

  $result = pw_blog_base_query()
    ->propertyOrderBy('created', 'DESC')
    ->pager(12)
    ->execute();

  if (!empty($result['node'])) {
    $build = node_view_multiple(node_load_multiple(array_keys($result['node'])), 'tile');
    $build['nodes']['#theme_wrappers'] = ['container__tiles'];
    $build['pager'] = [
      '#theme' => 'pager',
      '#weight' => 5,
    ];
  }

  return $build;
}

/**
 * Displays related bog posts.
 *
 * @return array
 *   The block render array.
 */
function pw_blog_related_blogposts_block() {
  $node = menu_get_object();

  if (!isset($node)) {
    return;
  }

  $block = [
    'subject' => t('Related blog posts'),
  ];

  $items = field_get_items('node', $node, 'field_blogpost_categories');

  if (empty($items)) {
    return;
  }

  $result = pw_blog_base_query()
    ->fieldCondition('field_blogpost_categories', 'tid', array_column($items, 'tid'), 'IN')
    ->propertyCondition('nid', $node->nid, '<>')
    ->propertyOrderBy('created', 'DESC')
    ->range(0, 3)
    ->execute();

  if (!empty($result['node'])) {
    $block['content'] = node_view_multiple(node_load_multiple(array_keys($result['node'])), 'tile');
  }

  return $block;
}

/**
 * Displays related bog posts.
 *
 * @return array
 *   The block render array.
 */
function pw_blog_recent_blogposts_block() {
  $block = [
    'subject' => t('New blog entries'),
  ];

  $result = pw_blog_base_query()
    ->propertyOrderBy('created', 'DESC')
    ->range(0, 3)
    ->execute();

  if (!empty($result['node'])) {
    $nodes = node_load_multiple(array_keys($result['node']));
    $block['content']['head'] = node_view(array_shift($nodes), 'tile');
    $block['content']['tail'] = node_view_multiple($nodes, 'tile');
    $block['content']['tail']['#theme_wrappers'] = ['container__small_tiles'];
  }

  return $block;
}

/**
 * Returns a query for fetching published nodes of type blogpost.
 *
 * @return EntityFieldQuery
 *   The query object.
 */
function pw_blog_base_query() {
  $q = new EntityFieldQuery();
  $q->entityCondition('entity_type', 'node');
  $q->entityCondition('bundle', 'blogpost');
  $q->propertyCondition('status', NODE_PUBLISHED);

  return $q;
}
