<?php

/**
 * @file
 * Code for the PW Search api feature.
 */
include_once 'pw_search_api.features.inc';

/**
 * Implements hook_node_presave().
 *
 * Sets sort date field depending on node type
 */
function pw_search_api_node_presave($node) {
  switch ($node->type) {
    case 'poll':
      $node->field_search_sort_date['und'][0]['value'] = $node->field_poll_date['und'][0]['value'];
      $node->field_search_sort_date['und'][0]['value2'] = $node->field_search_sort_date['und'][0]['value'];
      break;
    case 'blogpost':
      $node->field_search_sort_date['und'][0]['value'] = date("Y-m-d H:i:s", $node->created);
      $node->field_search_sort_date['und'][0]['value2'] = $node->field_search_sort_date['und'][0]['value'];
      break;
    case 'dialogue':
      $node->field_search_sort_date['und'][0]['value'] = date("Y-m-d H:i:s", $node->created);
      $node->field_search_sort_date['und'][0]['value2'] = $node->field_search_sort_date['und'][0]['value'];
      break;
    case 'page':
      $node->field_search_sort_date['und'][0]['value'] = date("Y-m-d H:i:s", $node->created);
      $node->field_search_sort_date['und'][0]['value2'] = $node->field_search_sort_date['und'][0]['value'];
      break;
    case 'pw_petition':
      // Petition dates are only updated on status change.
      $current_node = node_load($node->nid);
      if ($current_node->field_petition_status['und'][0]['value'] != $node->field_petition_status['und'][0]['value']) {
        $node->field_search_sort_date['und'][0]['value'] = date("Y-m-d H:i:s", $node->changed);
        $node->field_search_sort_date['und'][0]['value2'] = $node->field_search_sort_date['und'][0]['value'];
      }
      break;
  }
}

/**
 * Implements hook_search_api_processor_info().
 *
 * Registers preprocessor to add leading zero to 4-digit postal codes.
 */
function pw_search_api_search_api_processor_info() {
  $callbacks['add_leading_zero'] = array(
    'name' => t('Add leading zero'),
    'description' => t('Add leading zero to 4-digit area codes.'),
    'class' => 'SearchApiAddLeadingZero',
    'weight' => -1,
  );
  return $callbacks;
}

/**
 * Helper function to initialize the sort date for all relevant nodes,
 */
function pw_search_api_set_sort_date() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', ['pw_petition'], 'IN'); //,'blogpost','page','dialogue','pw_petition'
  $nodes = $query->execute();
  $i = 1;
  $ct = count($nodes['node']);
  foreach ($nodes['node'] as $node) {
    print('Updated Node ' . $node->nid . "\t(" . $i . ' of ' . $ct . ')' . PHP_EOL);
    $i++;
    $current_node = node_load($node->nid);
    node_save($current_node);
  }
}
