<?php

/**
 * @file
 * Code for the Profiles feature.
 */

include_once 'pw_profiles.features.inc';

/**
 * Implements hook_menu().
 */
function pw_profiles_menu() {
  $items['profiles/%taxonomy_term/%'] = [
    'title callback' => 'pw_profiles_page_title',
    'title arguments' => [1, 2],
    'page callback' => 'pw_profiles_page',
    'page arguments' => [1, 2],
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];
  $items['profiles/%taxonomy_term/%/autocomplete'] = [
    'page callback' => 'pw_profiles_autocomplete',
    'page arguments' => [1, 2],
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function pw_profiles_menu_alter(&$items) {
  $items['profile/%pw_profiles_username/archive/%'] = $items['user/%user/revisions/%/view'];
  $items['profile/%pw_profiles_username/archive/%']['access callback'] = 'user_view_access';
  $items['profile/%pw_profiles_username/archive/%']['access arguments'] = [1];
}

/**
 * Implements hook_page_delivery_callback_alter().
 */
function pw_profiles_page_delivery_callback_alter(&$callback) {
  if (menu_get_item()['page_callback'] != 'pw_profiles_page') {
    return;
  }

  // jQuery sets a HTTP_X_REQUESTED_WITH header of 'XMLHttpRequest'.
  // If a page would normally be delivered as an html page, and it is called
  // from jQuery, deliver it instead as an Ajax response.
  if (isset($_SERVER['HTTP_X_REQUESTED_WITH']) && $_SERVER['HTTP_X_REQUESTED_WITH'] == 'XMLHttpRequest' && $callback == 'drupal_deliver_html_page') {
    $callback = 'pw_globals_deliver_ajax_page';
  }
}

/**
 * Implements hook_form_alter().
 */
function pw_profiles_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    unset($form['locale']);
    unset($form['mimemail']);
    unset($form['overlay_control']);
    $form['#validate'][] = 'pw_profiles_form_validate';
    $form['account']['name']['#description'] = t('Only lowercase letters (a-z), numbers and dash are allowed.');

    // edit users UUID
    $role_admin = user_role_load_by_name('administrator');
    global $user;
    if ($role_admin && user_has_role($role_admin->rid, $user)) {
      $form['uuid'] = array(
        '#type' => 'textfield',
        '#title' => t('UUID'),
        '#default_value' => $form['#user']->uuid,
        '#required' => TRUE,
      );
    }

    // sort fields by parliament
    if(isset($form['field_user_parliament'][LANGUAGE_NONE]['#default_value'][0])){
      $parliament_tid = $form['field_user_parliament'][LANGUAGE_NONE]['#default_value'][0];
      foreach(array('field_user_constituency', 'field_user_list') as $field_name){
        if(isset($form[$field_name]['und']['#options'])){
          $form[$field_name]['und']['#options'] = _pw_sort_by_parliament($form[$field_name]['und']['#options'], $parliament_tid);
        }
      }
    }
  }
  elseif ($form_id == 'user_revision_edit_form') {
    unset($form['field_user_external_url']);
    unset($form['antispam_moderator']);
    unset($form['ckeditor']);
    unset($form['mimemail']);
    unset($form['overlay_control']);
    unset($form['xmlsitemap']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pw_profiles_form_pw_profiles_filters_form_alter(&$form, &$form_state) {
  $form['form_build_id']['#access'] = FALSE;
  $form['form_token']['#access'] = FALSE;
  $form['form_id']['#access'] = FALSE;
}

/**
 * Form validation handler for user_profile_form().
 *
 * @see pw_profiles_form_alter()
 */
function pw_profiles_form_validate($form, &$form_state) {
  if (isset($form_state['input']['name'])) {
    $username = $form_state['input']['name'];
    if (!preg_match('/^[a-z0-9\-]+$/', $username)) {
      form_set_error('name', $form['account']['name']['#description']);
    }
  }
  if (isset($form_state['input']['uuid'])) {
    $uuid = $form_state['input']['uuid'];
    if (!preg_match('/[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}/', $uuid)) {
      form_set_error('uuid', t('Please enter a valid UUID.'));
    }
    elseif ($user = entity_uuid_load('user', array($uuid))) {
      if($form['#user']->uid != key($user)){
        $user = array_pop($user);
        form_set_error('uuid', t('UUID already used by @name', ['@name' => l(_pw_get_fullname($user), 'user/' . $user->uid)]));
      }
    }
  }
}

/**
 * Implements hook_user_presave().
 *
 * FFI: Saves changes to the user role in the corresponding taxonomy.
 * This is important for the profile switch that relies on this taxonomy.
 */
function pw_profiles_user_presave(&$edit, $account, $category) {
  // fetch the chosen roles from $edit['roles']:
  $roleIdArray = [];

  // $edit['roles'] is unset if user_save() is called programmatically with
  // modifications that do not include the roles. In order to reset the roles
  // anyway, we load the roles from the $account:
  if (!isset($edit['roles'])) {
    foreach ($account->roles as $key => $value) {
      $edit['roles'][$key] = $key;
    }
  }
  foreach ($edit['roles'] as $key => $value) {
    if (!empty($value)) {
      $roleIdArray[] = $key;
    }
  }
  // reset the $edit['field_user_roles_for_view_mode_s']['und'] array:
  $edit['field_user_roles_for_view_mode_s']['und'] = [];

  foreach ($roleIdArray as $roleId) {
    $role = user_role_load($roleId);
    $roleName = $role->name; // i.e., Politician
    // search for this roleName in the taxonomy:
    $taxonomyArray = taxonomy_get_term_by_name($roleName, 'pw_profile_roles_for_view_mode_switch');
    foreach ($taxonomyArray as $taxonomy) {
      $tid = $taxonomy->tid;
      $edit['field_user_roles_for_view_mode_s']['und'][] = array('tid' => "$tid");
      break; // If there are several taxonomies with the same name that's a data error.
    }
  }
}

/**
 * Implements hook_user_load().
 */
function pw_profiles_user_load($users) {
  $vids = array_map(function ($account) { return $account->vid; }, $users);
  $q = db_select('user_archive_cache', 'uac')
    ->fields('uac', ['uid', 'number_of_questions', 'number_of_answers'])
    ->condition('vid', $vids, 'IN');

  foreach ($q->execute()->fetchAll() as $row) {
    $users[$row->uid]->number_of_questions = $row->number_of_questions;
    $users[$row->uid]->number_of_answers = $row->number_of_answers;
  }

}

/**
 *  Implements hook_user_update().
 */
function pw_profiles_user_update(&$edit, $account, $category) {

  // custom abort flag to prevent circular updates
  if(isset($account->abort_update) && $account->abort_update){
    return;
  }

  // check if username was changed and update path then
  if ($account->name != $account->original->name) {
    $path = path_load(array('source' => 'user/' . $account->uid));
    if ($path) {
      $path['alias'] = 'profile/' . $account->name;
      path_save($path);
    }
    $user_revisions = user_revision_list($account);
    foreach ($user_revisions as $user_revision) {
      if ($user_revision->name != $account->name) {
        $revision_edit = [];
        $revision_edit['name'] = $account->name;
        _user_revision_edit_save($user_revision, $revision_edit);
      }
    }
  }

}

/**
 * Implements hook_user_view().
 */
function pw_profiles_user_view($account, $view_mode, $langcode) {
  if ($view_mode == 'full' && _pw_user_has_role($account, 'Politician')) {
    $options = _pw_profiles_revision_switcher_options($account);

    if (!empty($options)) {
      $account->content['revisions'] = [
        '#theme' => 'select',
        '#options' => $options,
        '#value' => url(current_path()),
      ];
    }

    $account->content['#attached']['js'][drupal_get_path('module', 'pw_profiles') . '/twitter-widgets.js'] = [
      'type' => 'file',
    ];
  }

  if (in_array(menu_get_item()['page_callback'], ['user_view_page', 'user_revision_show'])) {
    $parliament_tid = pw_profiles_parliament($account)->tid;
    if (_pw_user_has_role($account, 'Deputy')) {
      menu_tree_set_path('main-menu', "profiles/$parliament_tid/deputies");
    }
    elseif (_pw_user_has_role($account, 'Candidate')) {
      menu_tree_set_path('main-menu', "profiles/$parliament_tid/candidates");
    }
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function pw_profiles_entity_info_alter(&$entity_info) {
  $entity_info['user']['view modes']['full'] = array(
    'label' => t('Full'),
    'custom settings' => FALSE,
  );
  $entity_info['user']['view modes']['list_item'] = array(
    'label' => t('List item'),
    'custom settings' => FALSE,
  );
  $entity_info['user']['view modes']['tile'] = array(
    'label' => t('Tile'),
    'custom settings' => FALSE,
  );
  $entity_info['user']['uri callback'] = 'pw_profiles_user_uri';
}

/**
 * Implements hook_theme().
 */
function pw_profiles_theme() {
  return [
    'profile_search_summary' => [
      'variables' => [
        'response' => NULL,
        'filters' => NULL,
        'role_name' => NULL,
      ],
    ],
  ];
}

/**
 * Entity URI callback; returns path to current or archived profile.
 *
 * @param object $user
 *   The user object
 *
 * @return array
 *   The path to a representation of the user revision
 */
function pw_profiles_user_uri($user) {
  if (isset($user->actual_profile) && $user->actual_profile == 0) {
    $path = 'profile/' . $user->name . '/archive/' . $user->vid;
  }
  else {
    $path = 'user/' . $user->uid;
  }
  return array(
    'path' => $path,
  );
}

/**
 * Page callback: Displays a list of profiles.
 *
 * Selects user revisions based on parliament and role.
 *
 * @param string $parliament_term
 *   The parliament term.
 * @param string $role_name
 *   The role.
 *
 * @return array
 *   The render array.
 */
function pw_profiles_page($parliament_term, $role_name) {
  $limit = 12;
  $q = pw_profiles_base_search_query($parliament_term, $role_name);

  if (isset(drupal_get_query_parameters()['constituency'])) {
    $f = new SearchApiQueryFilter('OR', ['facet:field_user_constituency']);
    $q->filter($f->condition('field_user_constituency', drupal_get_query_parameters()['constituency']));
  }

  if (isset(drupal_get_query_parameters()['list'])) {
    $f = new SearchApiQueryFilter('OR', ['facet:field_user_list']);
    $q->filter($f->condition('field_user_list', drupal_get_query_parameters()['list']));
  }

  if (isset(drupal_get_query_parameters()['list_position'])) {
    $f = new SearchApiQueryFilter('OR', ['facet:field_user_list_position']);
    $q->filter($f->condition('field_user_list_position', drupal_get_query_parameters()['list_position']));
  }

  if (isset(drupal_get_query_parameters()['party'])) {
    $f = new SearchApiQueryFilter('OR', ['facet:field_user_party']);
    foreach (drupal_get_query_parameters()['party'] as $party) {
      $f->condition('field_user_party', $party);
    }
    $q->filter($f);
  }

  if (isset(drupal_get_query_parameters()['gender'])) {
    $f = new SearchApiQueryFilter('OR', ['facet:field_user_gender']);
    foreach (drupal_get_query_parameters()['gender'] as $gender) {
      $f->condition('field_user_gender', $gender);
    }
    $q->filter($f);
  }

  if (isset(drupal_get_query_parameters()['keys'])) {
    $q->keys(drupal_get_query_parameters()['keys']);
  }

  $response = $q
    ->sort('has_picture', 'DESC')
    ->sort('number_of_answers', 'DESC')
    ->sort('number_of_questions', 'DESC')
    ->sort('field_user_lname')
    ->sort('search_api_relevance')
    ->range(pager_find_page() * $limit, $limit)
    ->execute();

  if (_pw_profiles_is_postal_code_search(drupal_get_query_parameters()) && count($response['search_api_facets']['field_user_constituency']) > 1) {
    drupal_add_http_header('Status', '300 Multiple Choices');
    $constituency_values = _pw_profiles_facet_values($response['search_api_facets']['field_user_constituency']);
    $build['constituency_selection'] = [
      '#theme_wrappers' => ['container__tiles'],
      '#theme' => 'item_list__constituency_selection',
      '#items' => _pw_profiles_constituency_selection_items($constituency_values, current_path(), drupal_get_query_parameters()),
    ];
  }
  elseif ($response['result count'] > 0) {
    pager_default_initialize($response['result count'], $limit);
    $politicians = pw_userarchives_politician_load_multiple(array_keys($response['results']));
    $weight = 0;
    foreach ($politicians as $vid => $politician) {
      $build['user'][$vid] = user_view($politician, 'tile');
      $build['user'][$vid]['#weight'] = ++$weight;
    }
    $build['user']['#theme_wrappers'] = ['container__tiles'];
    $build['user']['summary'] = [
      '#theme' => 'profile_search_summary',
      '#response' => $response,
      '#role_name' => $role_name,
      '#filters' => drupal_get_query_parameters(),
    ];
    $build['user']['pager'] = [
      '#theme' => 'pager',
      '#weight' => ++$weight,
    ];
  }
  else {
    $build['user'] = [
      '#markup' => t('Sorry, there are no results matching your query.'),
      '#theme_wrappers' => ['container__tiles']
    ];
  }

  $build['filters'] = drupal_get_form('pw_profiles_filters_form', $parliament_term, $response['search_api_facets'], isset($build['user']));
  $build['filters']['#weight'] = -5;
  $build['#theme_wrappers'] = ['container'];
  $build['#attributes'] = ['id' => 'ajax'];

  return $build;
}

/**
 * Page callback: Returns JSON object for autosuggest.
 *
 * @param object $parliament_term
 *   The parliament term.
 * @param type $role_name
 *   The role.
 */
function pw_profiles_autocomplete($parliament_term, $role_name) {
  $response = pw_profiles_base_search_query($parliament_term, $role_name)->execute();

  if ($response['result count'] > 0) {
    $suggestions = [];
    foreach ($response['results'] as $result) {
      $data = [
        'id' => $result['id'],
        'name' => $result['fields']['field_user_fname'] . ' ' . $result['fields']['field_user_lname'],
        'parliament' => $parliament_term->name,
        'party' => $result['fields']['field_user_party:name'],
        'url' => $result['fields']['url'],
      ];
      if (isset($result['fields']['picture_uri'])) {
        $data['picture_url'] = file_create_url(image_style_path('thumbnail', $result['fields']['picture_uri']));
      }
      else {
        $data['picture_url'] = 'http://via.placeholder.com/100x100';
      }
      $data['politicianDatum'] = $result['fields']['field_user_fname'] . ' ' . $result['fields']['field_user_lname'];
      if (isset($result['fields']['field_user_constituency:field_constituency_area_codes:name'])) {
        $data['politicianDatum'] .= ' ' . implode(' ', $result['fields']['field_user_constituency:field_constituency_area_codes:name']);
      }
      if (isset($result['fields']['field_user_constituency:field_constituency_ac_descriptor'])) {
        $data['politicianDatum'] .= ' ' . implode(' ', $result['fields']['field_user_constituency:field_constituency_ac_descriptor']);
      }
      if (isset($result['fields']['field_user_constituency:name'][0])) {
        $data['constituency'] = $result['fields']['field_user_constituency:name'];
        $data['politicianDatum'] .= ' ' . implode(' ', $result['fields']['field_user_constituency:name']);
      }
      $suggestions[] = $data;
    };
    drupal_json_output($suggestions);
  }
  else {
    return MENU_NOT_FOUND;
  }
}

/**
 * Title callback: Returns title for list of profiles.
 *
 * @param string $parliament
 *   The parliament name
 *
 * @param string $role_name
 *   The role
 *
 * @return string
 *   The title of the page
 */
function pw_profiles_page_title($parliament, $role_name) {
  if ($role_name == 'candidates') {
    return t('Candidates @parliament', ['@parliament' => $parliament->name]);
  }
  else {
    return t('Deputies @parliament', ['@parliament' => $parliament->name]);
  }
}

/**
 * Returns parliament term associated with the given account.
 *
 * Politician accounts are always associated with a parliament, whether they
 * are deputies or candidates.
 *
 * @param object $account
 *   The account object.
 *
 * @return object
 *   The parliament term.
 */
function pw_profiles_parliament($account) {
  $parliament_term = NULL;
  $items = field_get_items('user', $account, 'field_user_parliament');

  if ($items) {
    $parliament_term = taxonomy_term_load($items[0]['tid']);
  }

  return $parliament_term;
}

/**
 * Load all archived revisions of the given account.
 *
 * @param object $account
 *   The account object.
 *
 * @param string $direction
 *   The order direction (ascending by default).
 *
 * @return array
 *   An array of user (revision) objects.
 */
function pw_profiles_archived_revisions($account, $direction = 'ASC') {
  $revisions = [];

  $result = db_select('user_archive_cache', 'uac')
    ->fields('uac', ['vid'])
    ->condition('uid', $account->uid)
    ->orderBy('vid', $direction)
    ->execute();

  foreach ($result->fetchCol() as $vid) {
    $revisions[] = user_revision_load($account->uid, $vid);
  }

  return $revisions;
}

/**
 * Form constructor for the profile filters form.
 */
function pw_profiles_filters_form($form, &$form_state, $parliament, $facets, $additional_filters_enabled = TRUE) {

  $constituency_values = _pw_profiles_facet_values($facets['field_user_constituency']);
  $party_values = _pw_profiles_facet_values($facets['field_user_party']);
  $list_values = _pw_profiles_facet_values($facets['field_user_list']);
  $list_position_values = _pw_profiles_facet_values($facets['field_user_list_position']);
  $gender_options = array_combine(_pw_profiles_facet_values($facets['field_user_gender']), array_map('t', _pw_profiles_facet_values($facets['field_user_gender'])));

  $parameters = drupal_get_query_parameters();

  if (strpos($parliament->name, 'EU') === 0) {
    $keys_placeholder = t('Enter a locality or name');
  }
  else {
    $keys_placeholder = t('Enter a postal code, locality or name');
  }

  $form['#method'] = 'get';
  $form['#action'] = url(current_path());
  $form['#attributes']['data-ajax-target'] = '#ajax';
  $form['#theme'] = 'filterbar';
  $form['keys'] = [
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#title_display' => 'invisible',
    '#default_value' => isset($parameters['keys']) ? $parameters['keys'] : '',
    '#attributes' => ['placeholder' => $keys_placeholder],
  ];
  if (count($constituency_values) > 1) {
    $form['constituency'] = array(
      '#type' => 'select',
      '#title' => isset($parliament->field_parliament_constit_rename[LANGUAGE_NONE][0]['value']) ? $parliament->field_parliament_constit_rename[LANGUAGE_NONE][0]['value'] : t('Constituency'),
      '#title_display' => 'invisible',
      '#options' => ['' => t('All')] + _pw_profiles_options($constituency_values),
      '#default_value' => empty($parameters['constituency']) ? '' : $parameters['constituency'],
    );
  }
  if ($additional_filters_enabled) {
    if (count($list_values) > 1 && !pw_profiles_filter_disabled('field_user_list_tid', $parliament)) {
      $form['list'] = array(
        '#type' => 'radios',
        '#title' => isset($parliament->field_parliament_list_rename[LANGUAGE_NONE][0]['value']) ? $parliament->field_parliament_list_rename[LANGUAGE_NONE][0]['value'] : t('List'),
        '#title_display' => 'invisible',
        '#options' => ['' => t('All')] + _pw_profiles_options($list_values),
        '#default_value' => empty($parameters['list']) ? '' : $parameters['list'],
      );
    }
    if (count($list_position_values) > 1 && !pw_profiles_filter_disabled('field_user_list_position_tid', $parliament)) {
      $form['list_position'] = array(
        '#type' => 'select',
        '#title' => t('List position'),
        '#title_display' => 'invisible',
        '#options' => ['' => t('All')] + _pw_profiles_options($list_position_values),
        '#default_value' => empty($parameters['list_position']) ? '' : $parameters['list_position'],
      );
    }
    if (count($party_values) > 1) {
      $form['party'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Filter by party'),
        '#title_display' => 'invisible',
        '#options' => _pw_profiles_options($party_values),
        '#multiple' => TRUE,
        '#default_value' => empty($parameters['party']) ? [] : $parameters['party'],
      );
    }
    if (count($gender_options) > 1) {
      $form['gender'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Gender'),
        '#title_display' => 'invisible',
        '#options' => $gender_options,
        '#default_value' => empty($parameters['gender']) ? [] : $parameters['gender'],
      );
    }
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Filter profiles'),
  );

  return $form;
}

/**
 * Returns TRUE if the filter is disabled for the parliament, FALSE otherwise.
 *
 * @param string $filter
 *
 * @param object $parliament
 *
 * @return bool
 */
function pw_profiles_filter_disabled($filter, $parliament) {
  $items = field_get_items('taxonomy_term', $parliament, 'field_parliament_filter_disabled');

  if (is_array($items)) {
    foreach ($items as $item) {
      if ($item['value'] == $filter) {
        return TRUE;
      }
    }
  }

  return FALSE;
}

/**
 * Returns the account object identified by the given name.
 *
 * @param string $name
 *   The username.
 *
 * @return object
 *   An account object with the given name.
 */
function pw_profiles_username_load($name) {
  return user_load_by_name($name);
}

/**
 * Returns a query object for fetching politicians.
 *
 * @param type $parliament_term
 *   The parliament term.
 * @param type $role_name
 *   The role (candidates or deputies).
 *
 * @return SearchApiQuery
 *   The search query object.
 */
function pw_profiles_base_search_query($parliament_term, $role_name) {
  $q = search_api_query('politician_archive_index', ['search_api_facets' => _pw_profiles_facets()]);
  $q->condition('field_user_retired', NULL, '=');
  $q->condition('field_user_parliament', $parliament_term->tid);

  if ($role_name == 'deputies') {
    $q->condition('field_user_roles_for_view_mode_s', PW_GLOBALS_DEPUTY_TID);
  }
  else {
    $q->condition('field_user_roles_for_view_mode_s', PW_GLOBALS_CANDIDATE_TID);
  }
  return $q;
}

/**
 * Returns list of facets for the profile page.
 *
 * @return array
 *   An associative array to be used as facets option for a query.
 */
function _pw_profiles_facets() {
  $common = ['limit' => -1, 'min_count' => 1, 'missing' => TRUE, 'operator' => 'or'];
  return [
    'field_user_list' => ['field' => 'field_user_list'] + $common,
    'field_user_list_position' => ['field' => 'field_user_list_position'] + $common,
    'field_user_gender' => ['field' => 'field_user_gender'] + $common,
    'field_user_party' => ['field' => 'field_user_party'] + $common,
    'field_user_constituency' => ['field' => 'field_user_constituency'] + $common,
  ];
}

/**
 * Extracts the values from a facet.
 *
 * This function also removes the additional double quotes around the value.
 *
 * @param array $facet
 *   The facet.
 *
 * @return array
 *   An array of values for filtering the result.
 */
function _pw_profiles_facet_values($facet) {
  $values = [];

  foreach ($facet as $result) {
    if ($result['filter'] != '!') {
      $values[] = trim($result['filter'], '"');
    }
  }

  return $values;
}

/**
 * Returns taxonomy term options for the given term IDs.
 *
 * @param array $values
 *   An array of taxonomy term IDs
 *
 * @return array
 *   An array of taxonomy term names keyed by term ID.
 */
function _pw_profiles_options(array $values) {
  static $terms = [];

  if (empty($terms)) {
    $terms = db_select('taxonomy_term_data', 't')
      ->fields('t', array('tid', 'name'))
      ->condition('vid', array(17, 19, 32, 38, 39), 'IN')
      ->execute()
      ->fetchAllKeyed();
    natsort($terms);
  }

  return array_intersect_key($terms, array_flip($values));
}

/**
 * Returns constituency descriptors grouped by constituency.
 *
 * @param array $constituency_values
 *   An array of constituency term IDs.
 * @param string $url
 *   The URL.
 * @param array $parameters
 *   The query parameters.
 *
 * @return
 *   An array of constituency descriptors keyed by term ID.
 */
function _pw_profiles_constituency_selection_items(array $constituency_values, $url, $parameters) {
  $items = [];

  foreach (taxonomy_term_load_multiple($constituency_values) as $term) {
    $parameters['constituency'] = $term->tid;
    $descriptor_items = field_get_items('taxonomy_term', $term, 'field_constituency_ac_descriptor');
    if (!$descriptor_items) {
      $items[] = ['data' => $term->name, url($url, ['query' => $parameters])];
    }
    else {
      foreach (explode(',', rtrim($descriptor_items[0]['safe_value'], ',')) as $descriptor) {
        list($postal_code, $locality) = explode(':', $descriptor);
        if ($postal_code == $parameters['keys']) {
          $items[] = ['data' => $locality, 'href' => url($url, ['query' => $parameters])];
        }
      }
    }
  }

  return $items;
}

/**
 * Returns an associative array to be used as options for a select box.
 *
 * @param object $account
 *   The account object.
 *
 * @return array
 *   An array with URLs as keys and labels for the legislative terms as values.
 */
function _pw_profiles_revision_switcher_options($account) {
  $options = [];

  foreach (pw_profiles_archived_revisions($account, 'DESC') as $revision) {
    if (in_array(PW_GLOBALS_DEPUTY_RID, array_keys($revision->roles))) {
      $text = pw_profiles_parliament($revision)->name;
    }
    else {
      $text = preg_replace('/\-\d+\s*$/', '', pw_profiles_parliament($revision)->name) . ' (Wahlen)';
    }
    $options[url(entity_uri('user', $revision)['path'])] = $text;
  }
  return $options;
}

/**
 * Returns whether the given search is exclusively for a postal code.
 *
 * @param array $parameters
 *   The query parameters
 *
 * @return bool
 *   TRUE if $parameters['keys'] matches the postal code pattern and there
 *   are no other search parameters, FALSE otherwise.
 */
function _pw_profiles_is_postal_code_search($parameters) {
  if (!isset($parameters['keys'])) {
    return FALSE;
  }
  if (count(array_filter($parameters)) > 1) {
    return FALSE;
  }
  return preg_match('/^[0-9]{4,5}$/', trim($parameters['keys']));
}

/**
 * Returns HTML for a summary of the search result.
 *
 * @param array $variables
 *   An associative array containing:
 *   - response
 *   - role_name
 *   - filters
 */
function theme_profile_search_summary(&$variables) {
  $output = '';
  $facets = $variables['response']['search_api_facets'];
  $link_options = ['attributes' => ['data-ajax-target' => '#ajax']];

  $options['@count'] = $variables['response']['result count'];
  $options['!gender'] = '';

  if (!empty($variables['filters']['gender'])) {
    if (count($variables['filters']['gender']) == 1) {
      $value = reset($variables['filters']['gender']);
      $text = format_plural($variables['response']['result count'], $value, $value, [], ['context' => 'search-summary']);
      $options['!gender'] = l($text, current_path(), $link_options + ['query' => _pw_profiles_reject_filter($variables['filters'], 'gender')]);
    }
    elseif ($variables['filters']['gender'] == ['male' => 'male', 'female' => 'female']) {
      $text = format_plural($variables['response']['result count'], 'female or male', 'female and male', [], ['context' => 'search-summary']);
      $options['!gender'] = l($text, current_path(), $link_options + ['query' => _pw_profiles_reject_filter($variables['filters'], 'gender')]);
    }
  }

  if (!empty($variables['filters']['party'])) {
    $parties_count = count($variables['filters']['party']);
    $parties_text = format_plural($parties_count, '1 party', '@count parties');
    $options['!parties'] = l($parties_text, current_path(), $link_options + ['query' => _pw_profiles_reject_filter($variables['filters'], 'party')]);
  }
  else {
    $parties_count = count(_pw_profiles_facet_values($facets['field_user_party']));
    $parties_text = format_plural($parties_count, '1 party', '@count parties');
    $options['!parties'] = $parties_text;
  }

  if (!empty($variables['filters']['constituency'])) {
    $constituencies_count = 1;
    $constituencies_text = format_plural($constituencies_count, '1 constituency', '@count constituencies');
    $options['!constituencies'] = l($constituencies_text, current_path(), $link_options + ['query' => _pw_profiles_reject_filter($variables['filters'], 'constituency')]);
  }
  else {
    $constituencies_count = count(_pw_profiles_facet_values($facets['field_user_constituency']));
    $constituencies_text = format_plural($constituencies_count, '1 constituency', '@count constituencies');
    $options['!constituencies'] = $constituencies_text;
  }

  $output .= '<p>';

  if ($variables['role_name'] == 'candidates') {
    $output .= t('Found @count !gender candidates from !parties and !constituencies.', $options);
  }
  else {
    $output .= t('Found @count !gender deputies from !parties and !constituencies.', $options);
  }

  if (!empty($variables['filters']['keys'])) {
    $options['!keys'] = l(check_plain($variables['filters']['keys']), current_path(), $link_options + ['query' => _pw_profiles_reject_filter($variables['filters'], 'keys')]);
    $output .= ' ' . t('You have searched for: !keys', $options);
  }

  if (!empty(array_filter($variables['filters']))) {
    $output .= ' ' . l(t('Reset all filters'), current_path(), $link_options);
  }

  $output .= '</p>';

  return $output;
}

/**
 * Removes the filter with the given key.
 *
 * @param array $filters
 *   The filters.
 * @param string $key
 *
 * @return array
 *   The filters without the given key.
 */
function _pw_profiles_reject_filter(array $filters, $key, $value = NULL) {
  if (array_key_exists($key, $filters)) {
    if (!isset($value)) {
      unset($filters[$key]);
    }
    else {
      unset($filters[$key][array_search($value, $filters[$key])]);
    }
  }
  return array_filter($filters);
}
