<?php

/**
 * @file
 * Code for the Profiles feature.
 */

include_once 'pw_profiles.features.inc';

/**
 * Implements hook_init().
 *
 * Hides profile pages of non-politicians from anonymous users.
 */
function pw_profiles_init() {
  if (menu_get_item()['page_callback'] == 'user_revision_show') {
    $map = menu_get_item()['original_map'];
    $account = user_revision_load($map[1], $map[3]);
  }
  else {
    $account = menu_get_object('user');
  }

  $is_profile_page = in_array(menu_get_item()['page_callback'], ['user_view_page', 'user_revision_show']);

  if ($is_profile_page && !_pw_user_has_role($account, 'Politician') && !user_is_logged_in()) {
    drupal_not_found();
  }
}

/**
 * Implements hook_menu().
 */
function pw_profiles_menu() {
  $items['profiles/%taxonomy_term/%'] = [
    'title callback' => 'pw_profiles_page_title',
    'title arguments' => [1, 2],
    'page callback' => 'pw_profiles_page',
    'page arguments' => [1, 2],
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];
  $items['profiles/%taxonomy_term/%/autocomplete'] = [
    'page callback' => 'pw_profiles_autocomplete',
    'page arguments' => [1, 2],
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];
  $items['profiles/%taxonomy_term/%/street-search'] = [
    'page callback' => 'pw_profiles_street_search',
    'page arguments' => [1, 2],
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function pw_profiles_menu_alter(&$items) {
  $items['profile/%pw_profiles_username/archive/%'] = $items['user/%user/revisions/%/view'];
  $items['profile/%pw_profiles_username/archive/%']['access callback'] = 'user_view_access';
  $items['profile/%pw_profiles_username/archive/%']['access arguments'] = [1];
}

/**
 * Implements hook_token_info_alter().
 */
function pw_profiles_token_info_alter(&$data) {
  $data['tokens']['user']['constituency'] = [
    'name' => t('Constituency'),
    'description' => t('The formatted constituency of the user account.'),
  ];
}

/**
 * Implements hook_tokens().
 */
function pw_profiles_tokens($type, $tokens, array $data = [], array $options = []) {
  $replacements = [];

  if ($type == 'user' && !empty($data['user'])) {
    $account = $data['user'];

    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'constituency':
          if (isset($account->field_user_constituency[LANGUAGE_NONE][0]['tid'])) {
            $constituency = taxonomy_term_load($account->field_user_constituency[LANGUAGE_NONE][0]['tid']);
            $placeholders = [
              '@number' => $constituency->field_constituency_nr[LANGUAGE_NONE][0]['value'],
              '@title' => $constituency->name,
            ];
            $parliament = pw_profiles_parliament($data['user']);
            if (strpos($parliament->name, 'Bayern') === 0) {
              $replacements[$original] = t('Constituency @number: @title', $placeholders, ['context' => 'Bayern']) . ',';
            } else {
              $replacements[$original] = t('Constituency @number: @title', $placeholders, ['context' => '']) . ',';
            }
          }
          else {
            $replacements[$original] = '';
          }
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_page_delivery_callback_alter().
 *
 * In order to ensure caching mechanisms store a distinct copy for AJAX
 * responses the parameter ajax needs to be present. For caches evaluating Vary
 * headers one would usually add Vary: X-Requested-With to the HTTP headers.
 * Drupal's internal page cache uses only the request URI as an identifier
 * though.
 */
function pw_profiles_page_delivery_callback_alter(&$callback) {
  if (!isset(drupal_get_query_parameters()['ajax'])) {
    return;
  }

  if (menu_get_item()['page_callback'] != 'pw_profiles_page') {
    return;
  }

  // jQuery sets a HTTP_X_REQUESTED_WITH header of 'XMLHttpRequest'.
  // If a page would normally be delivered as an html page, and it is called
  // from jQuery, deliver it instead as an Ajax response.
  if (isset($_SERVER['HTTP_X_REQUESTED_WITH']) && $_SERVER['HTTP_X_REQUESTED_WITH'] == 'XMLHttpRequest' && $callback == 'drupal_deliver_html_page') {
    $callback = 'pw_globals_deliver_ajax_page';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pw_profiles_form_user_profile_form_alter(&$form, &$form_state) {
  unset($form['locale']);
  unset($form['mimemail']);
  unset($form['overlay_control']);
  $form['#validate'][] = 'pw_profiles_form_validate';
  $form['account']['name']['#description'] = t('Only lowercase letters (a-z), numbers and dash are allowed.');

  $role_admin = user_role_load_by_name('administrator');
  global $user;
  if ($role_admin && user_has_role($role_admin->rid, $user)) {
    $form['uuid'] = array(
      '#type' => 'textfield',
      '#title' => t('UUID'),
      '#default_value' => $form['#user']->uuid,
      '#required' => TRUE,
    );
  }

  if (isset($form['field_user_parliament'][LANGUAGE_NONE]['#default_value'][0])) {
    foreach (['field_user_constituency', 'field_user_list'] as $field_name) {
      if (isset($form[$field_name][LANGUAGE_NONE]['#options'])) {
        $form[$field_name][LANGUAGE_NONE]['#options'] = _pw_profiles_filter_options($form[$field_name][LANGUAGE_NONE]['#options'], $form['#user']);
      }
    }
  }

  if (isset($form['field_user_list_position'][LANGUAGE_NONE]['#options'])) {
    asort($form['field_user_list_position'][LANGUAGE_NONE]['#options']);
    unset($form['field_user_list_position'][LANGUAGE_NONE]['#options']['_none']);
  }

  if (_pw_user_has_role($form_state['user'], 'Politician')) {
    $form['qa_hint'] = [
      '#type' => 'fieldset',
      '#title' => t('Answer questions'),
      '#description' => t('Questions are sent to you via email and can only be answered via email.'),
      '#attributes' => ['style' => 'border: solid 3px #ed541d'],
      '#weight' => $form['#groups']['group_user_personal_data']->weight - 0.5,
    ];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pw_profiles_form_user_revision_edit_form_alter(&$form, &$form_state) {
  unset($form['field_user_external_url']);
  unset($form['antispam_moderator']);
  unset($form['ckeditor']);
  unset($form['mimemail']);
  unset($form['overlay_control']);
  unset($form['xmlsitemap']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pw_profiles_form_pw_profiles_filters_form_alter(&$form, &$form_state) {
  $form['form_build_id']['#access'] = FALSE;
  $form['form_token']['#access'] = FALSE;
  $form['form_id']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pw_profiles_form_pw_profiles_street_form_alter(&$form, &$form_state) {
  $form['form_build_id']['#access'] = FALSE;
  $form['form_token']['#access'] = FALSE;
  $form['form_id']['#access'] = FALSE;
}

/**
 * Implements hook_metatag_metatags_view_alter().
 */
function pw_profiles_metatag_metatags_view_alter(&$output, $instance, $options) {
  if ($instance == 'user:user') {
    $canonical_url = url(user_uri($options['entity'])['path'], ['absolute' => TRUE, 'base_url' => 'https://www.abgeordnetenwatch.de']);
    $output['canonical']['#attached']['drupal_add_html_head'][0][0]['#value'] = $canonical_url;
    $output['canonical']['#attached']['drupal_add_html_head'][0][0]['#attached']['drupal_add_http_header'][0][1] = '<' . $canonical_url .'>; rel=canonical';
  }
}

/**
 * Form validation handler for user_profile_form().
 *
 * @see pw_profiles_form_alter()
 */
function pw_profiles_form_validate($form, &$form_state) {
  if (isset($form_state['input']['name'])) {
    $username = $form_state['input']['name'];
    if (!preg_match('/^[a-z0-9\-]+$/', $username)) {
      form_set_error('name', $form['account']['name']['#description']);
    }
  }
  if (isset($form_state['input']['uuid'])) {
    $uuid = $form_state['input']['uuid'];
    if (!preg_match('/[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}/', $uuid)) {
      form_set_error('uuid', t('Please enter a valid UUID.'));
    }
    elseif ($user = entity_uuid_load('user', array($uuid))) {
      if($form['#user']->uid != key($user)){
        $user = array_pop($user);
        form_set_error('uuid', t('UUID already used by @name', ['@name' => l(_pw_get_fullname($user), 'user/' . $user->uid)]));
      }
    }
  }
}

/**
 * Implements hook_user_presave().
 *
 * FFI: Saves changes to the user role in the corresponding taxonomy.
 * This is important for the profile switch that relies on this taxonomy.
 */
function pw_profiles_user_presave(&$edit, $account, $category) {
  // fetch the chosen roles from $edit['roles']:
  $roleIdArray = [];

  // $edit['roles'] is unset if user_save() is called programmatically with
  // modifications that do not include the roles. In order to reset the roles
  // anyway, we load the roles from the $account:
  if (!isset($edit['roles'])) {
    foreach ($account->roles as $key => $value) {
      $edit['roles'][$key] = $key;
    }
  }
  foreach ($edit['roles'] as $key => $value) {
    if (!empty($value)) {
      $roleIdArray[] = $key;
    }
  }
  // reset the $edit['field_user_roles_for_view_mode_s']['und'] array:
  $edit['field_user_roles_for_view_mode_s']['und'] = [];

  foreach ($roleIdArray as $roleId) {
    $role = user_role_load($roleId);
    $roleName = $role->name; // i.e., Politician
    // search for this roleName in the taxonomy:
    $taxonomyArray = taxonomy_get_term_by_name($roleName, 'pw_profile_roles_for_view_mode_switch');
    foreach ($taxonomyArray as $taxonomy) {
      $tid = $taxonomy->tid;
      $edit['field_user_roles_for_view_mode_s']['und'][] = array('tid' => "$tid");
      break; // If there are several taxonomies with the same name that's a data error.
    }
  }
}

/**
 * Implements hook_user_load().
 */
function pw_profiles_user_load($users) {
  $vids = array_map(function ($account) { return $account->vid; }, $users);
  $q = db_select('user_archive_cache', 'uac')
    ->fields('uac', ['uid', 'number_of_questions', 'number_of_answers'])
    ->condition('vid', $vids, 'IN');

  foreach ($q->execute()->fetchAll() as $row) {
    $users[$row->uid]->number_of_questions = $row->number_of_questions;
    $users[$row->uid]->number_of_answers = $row->number_of_answers;
  }

}

/**
 *  Implements hook_user_update().
 */
function pw_profiles_user_update(&$edit, $account, $category) {

  // custom abort flag to prevent circular updates
  if(isset($account->abort_update) && $account->abort_update){
    return;
  }

  // check if username was changed and update path then
  if ($account->name != $account->original->name) {
    $path = path_load(array('source' => 'user/' . $account->uid));
    if ($path) {
      $path['alias'] = 'profile/' . $account->name;
      path_save($path);
    }
    $user_revisions = user_revision_list($account);
    foreach ($user_revisions as $user_revision) {
      if ($user_revision->name != $account->name) {
        $revision_edit = [];
        $revision_edit['name'] = $account->name;
        _user_revision_edit_save($user_revision, $revision_edit);
      }
    }
  }

}

/**
 * Implements hook_user_view().
 */
function pw_profiles_user_view($account, $view_mode, $langcode) {
  if ($view_mode == 'full' && _pw_user_has_role($account, 'Politician')) {
    $items = _pw_profiles_revision_dropdown($account);

    if (!empty($items)) {
      $account->content['revisions'] = [
        '#theme' => 'item_list__politician_dropdown',
        '#items' => $items
      ];
    }

    $account->content['#attached']['js'][drupal_get_path('module', 'pw_profiles') . '/twitter-widgets.js'] = [
      'type' => 'file',
    ];
  }

  if (in_array(menu_get_item()['page_callback'], ['user_view_page', 'user_revision_show'])) {
    $parliament_tid = pw_profiles_parliament($account)->tid;
    if (_pw_user_has_role($account, 'Deputy')) {
      menu_tree_set_path('main-menu', "profiles/$parliament_tid/deputies");
    }
    elseif (_pw_user_has_role($account, 'Candidate')) {
      menu_tree_set_path('main-menu', "profiles/$parliament_tid/candidates");
    }
  }

  if (isset($account->content['field_user_constituency'])) {
    if (strpos(pw_profiles_parliament($account)->name, 'Bayern') === 0) {
      $account->content['field_user_constituency']['#title'] = t('Constituency', [], ['context' => 'Bayern']);
    }
  }

  if (isset($account->content['field_user_list'])) {
    if (strpos(pw_profiles_parliament($account)->name, 'Bayern') === 0) {
      $account->content['field_user_list']['#title'] = t('List', [], ['context' => 'Bayern']);
    }
  }

  if (isset($account->content['field_user_election_result'])) {
    if (strpos(pw_profiles_parliament($account)->name, 'Bayern') === 0) {
      $constituency_context = 'Bayern';
      $list_context = 'Bayern';
    }
    elseif (strpos(pw_profiles_parliament($account)->name, 'Baden-Württemberg') === 0) {
      $constituency_context = '';
      $list_context = 'Baden-Württemberg';
    }
    else {
      $constituency_context = '';
      $list_context = '';
    }

    $account->content['field_user_election_result'][0]['#title'] = t('Constituency result', [], ['context' => $constituency_context]);

    if ($account->content['field_user_constituency_won']['#items'][0]['value'] == 1) {
      $account->content['field_user_election_result'][0]['#markup'] = t('@result % (via constituency)', ['@result' => $account->content['field_user_election_result']['#items'][0]['value']], ['context' => $constituency_context]);
    }
    elseif ($account->content['field_user_list_won']['#items'][0]['value'] == 1) {
      $account->content['field_user_election_result'][0]['#markup'] = t('@result % (via list)', ['@result' => $account->content['field_user_election_result']['#items'][0]['value']], ['context' => $list_context]);
    }
    else {
      $account->content['field_user_election_result'][0]['#markup'] = t('@result %', ['@result' => $account->content['field_user_election_result']['#items'][0]['value']]);
    }
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function pw_profiles_entity_info_alter(&$entity_info) {
  $entity_info['user']['view modes']['full'] = array(
    'label' => t('Full'),
    'custom settings' => FALSE,
  );
  $entity_info['user']['view modes']['list_item'] = array(
    'label' => t('List item'),
    'custom settings' => FALSE,
  );
  $entity_info['user']['view modes']['tile'] = array(
    'label' => t('Tile'),
    'custom settings' => FALSE,
  );
  $entity_info['user']['uri callback'] = 'pw_profiles_user_uri';
}

/**
 * Implements hook_theme().
 */
function pw_profiles_theme() {
  return [
    'profile_search_summary' => [
      'variables' => [
        'response' => NULL,
        'filters' => NULL,
        'role_name' => NULL,
        'parliament' => NULL,
      ],
    ],
  ];
}

/**
 * Entity URI callback; returns path to current or archived profile.
 *
 * @param object $user
 *   The user object
 *
 * @return array
 *   The path to a representation of the user revision
 */
function pw_profiles_user_uri($user) {
  if (isset($user->actual_profile) && $user->actual_profile == 0) {
    $path = 'profile/' . $user->name . '/archive/' . $user->vid;
  }
  else {
    $path = 'user/' . $user->uid;
  }
  return array(
    'path' => $path,
  );
}

/**
 * Page callback: Displays a list of profiles.
 *
 * Selects user revisions based on parliament and role.
 *
 * @param string $parliament_term
 *   The parliament term.
 * @param string $role_name
 *   The role.
 *
 * @return array
 *   The render array.
 */
function pw_profiles_page($parliament_term, $role_name) {
  $limit = 12;
  $q = pw_profiles_base_search_query($parliament_term, $role_name);

  if (isset(drupal_get_query_parameters()['constituency'])) {
    $f = new SearchApiQueryFilter('OR', ['facet:field_user_constituency']);
    $q->filter($f->condition('field_user_constituency', drupal_get_query_parameters()['constituency']));
  }

  if (isset(drupal_get_query_parameters()['list'])) {
    $f = new SearchApiQueryFilter('OR', ['facet:field_user_list']);
    $q->filter($f->condition('field_user_list', drupal_get_query_parameters()['list']));
  }

  if (isset(drupal_get_query_parameters()['list_position'])) {
    $f = new SearchApiQueryFilter('OR', ['facet:field_user_list_position']);
    $q->filter($f->condition('field_user_list_position', drupal_get_query_parameters()['list_position']));
  }

  if (isset(drupal_get_query_parameters()['party'])) {
    $f = new SearchApiQueryFilter('OR', ['facet:field_user_party']);
    foreach (drupal_get_query_parameters()['party'] as $party) {
      $f->condition('field_user_party', $party);
    }
    $q->filter($f);
  }

  if (isset(drupal_get_query_parameters()['gender'])) {
    $f = new SearchApiQueryFilter('OR', ['facet:field_user_gender']);
    foreach (drupal_get_query_parameters()['gender'] as $gender) {
      $f->condition('field_user_gender', $gender);
    }
    $q->filter($f);
  }

  if (isset(drupal_get_query_parameters()['keys'])) {
    $q->keys(drupal_get_query_parameters()['keys']);
  }

  $response = $q
    ->sort('number_of_answers', 'DESC')
    ->sort('number_of_questions', 'DESC')
    ->sort('has_picture', 'DESC')
    ->sort('field_user_lname')
    ->sort('search_api_relevance')
    ->range(pager_find_page() * $limit, $limit)
    ->execute();

  if (_pw_profiles_is_postal_code_search(drupal_get_query_parameters()) && _pw_profiles_street_required(drupal_get_query_parameters(), $parliament_term)) {
    drupal_add_http_header('Status', '300 Multiple Choices');
    $build['constituency_selection'] = drupal_get_form('pw_profiles_street_form', $parliament_term, drupal_get_query_parameters());
    $build['constituency_selection']['#theme_wrappers'][] = 'container__tiles';
  }
  elseif (_pw_profiles_is_postal_code_search(drupal_get_query_parameters()) && count($response['search_api_facets']['field_user_constituency']) > 1) {
    drupal_add_http_header('Status', '300 Multiple Choices');
    $constituency_values = _pw_profiles_facet_values($response['search_api_facets']['field_user_constituency']);
    $build['constituency_selection'] = [
      '#theme_wrappers' => ['container__tiles'],
      '#theme' => 'item_list__constituency_selection',
      '#items' => _pw_profiles_constituency_selection_items($constituency_values, current_path(), drupal_get_query_parameters()),
    ];
  }
  else {
    pager_default_initialize($response['result count'], $limit);
    $politicians = pw_userarchives_politician_load_multiple(array_keys($response['results']));
    $weight = 0;
    foreach ($politicians as $vid => $politician) {
      $build['user'][$vid] = user_view($politician, 'tile');
      $build['user'][$vid]['#weight'] = ++$weight;
    }
    $build['user']['#theme_wrappers'] = ['container__tiles'];
    $build['user']['summary'] = [
      '#theme' => 'profile_search_summary',
      '#response' => $response,
      '#role_name' => $role_name,
      '#filters' => drupal_get_query_parameters(),
      '#parliament' => $parliament_term,
    ];
    $build['user']['pager'] = [
      '#theme' => 'pager',
      '#weight' => ++$weight,
    ];
  }

  $build['filters'] = drupal_get_form('pw_profiles_filters_form', $parliament_term, $response['search_api_facets'], isset($build['user']));
  $build['filters']['#theme_wrappers'][] = 'container__filterbar';
  $build['filters']['#weight'] = -5;
  $build['#theme_wrappers'] = ['container'];
  $build['#attributes'] = ['id' => 'ajax'];

  return $build;
}

/**
 * Page callback: Returns JSON object for autosuggest.
 *
 * @param object $parliament_term
 *   The parliament term.
 * @param type $role_name
 *   The role.
 *
 * @return string
 *   The JSON object for autosuggest.
 */
function pw_profiles_autocomplete($parliament_term, $role_name) {
  $response = pw_profiles_base_search_query($parliament_term, $role_name)->execute();

  if ($response['result count'] > 0) {
    $suggestions = [];
    foreach ($response['results'] as $result) {
      $data = [
        'id' => $result['id'],
        'name' => $result['fields']['field_user_fname'] . ' ' . $result['fields']['field_user_lname'],
        'parliament' => $parliament_term->name,
        'party' => $result['fields']['field_user_party:name'],
        'url' => $result['fields']['url'],
      ];
      if (isset($result['fields']['picture_uri'])) {
        $data['picture_url'] = file_create_url(image_style_path('thumbnail', $result['fields']['picture_uri']));
      }
      else {
        $data['picture_url'] = 'http://via.placeholder.com/100x100';
      }
      $data['politicianDatum'] = $result['fields']['field_user_fname'] . ' ' . $result['fields']['field_user_lname'];
      if (isset($result['fields']['field_user_constituency:name'][0])) {
        $data['constituency'] = $result['fields']['field_user_constituency:name'];
      }
      $suggestions[] = $data;
    }
    drupal_json_output($suggestions);
  }
  else {
    return MENU_NOT_FOUND;
  }
}

/**
 * Title callback: Returns title for list of profiles.
 *
 * @param object $parliament
 *   The parliament term.
 * @param string $role_name
 *   The role.
 *
 * @return string
 *   The title of the page
 */
function pw_profiles_page_title($parliament, $role_name) {
  if ($role_name == 'candidates') {
    return t('Candidates @parliament', ['@parliament' => $parliament->name]);
  }
  else {
    return t('Deputies @parliament', ['@parliament' => $parliament->name]);
  }
}

/**
 * Page callback: Returns options for selecting a constituency by street address.
 *
 * @param object $parliament
 *   The parliament term.
 * @param string $postal_code
 *   The postal code.
 *
 * @return string
 *   The JSON data for selecting a constituency.
 */
function pw_profiles_street_search($parliament, $postal_code) {
  $matches = [];

  $q = db_select('field_data_field_constituency_area_codes', 'ac');
  $q->join('field_data_field_parliament', 'p', 'ac.entity_id = p.entity_id AND p.bundle = :bundle', [':bundle' => 'constituency']);
  $q->join('field_data_field_constituency_street', 's', 'ac.entity_id = s.entity_id');
  $q->join('taxonomy_term_data', 'td', 'ac.field_constituency_area_codes_tid = td.tid');
  $q->fields('s', ['field_constituency_street_value', 'entity_id'])
    ->condition('td.name', $postal_code)
    ->condition('p.field_parliament_tid', $parliament->tid)
    ->orderBy('s.field_constituency_street_value');

  if (isset(drupal_get_query_parameters()['term'])) {
    $q->condition('s.field_constituency_street_value', drupal_get_query_parameters()['term'] . '%', 'LIKE');
  }

  $result = $q->execute();

  foreach ($result as $row) {
    $matches[] = [
      'id' => $row->entity_id,
      'text' => $row->field_constituency_street_value,
    ];
  }

  drupal_json_output(['results' => $matches]);
}


/**
 * Returns parliament term associated with the given account.
 *
 * Politician accounts are always associated with a parliament, whether they
 * are deputies or candidates.
 *
 * @param object $account
 *   The account object.
 *
 * @return object
 *   The parliament term.
 */
function pw_profiles_parliament($account) {
  $parliament_term = NULL;
  $items = field_get_items('user', $account, 'field_user_parliament');

  if ($items) {
    $parliament_term = taxonomy_term_load($items[0]['tid']);
  }

  return $parliament_term;
}

/**
 * Load earlier (or later) revisions of the given account.
 *
 * @param object $account
 *   The account object.
 *
 * @param bool $earlier
 *   Whether earlier or later revisions should be returned.
 *
 * @return array
 *   An array of user (revision) objects.
 */
function pw_profiles_archived_revisions($account, $earlier = TRUE) {
  $revisions = [];

  $result = db_select('user_archive_cache', 'uac')
    ->fields('uac', ['vid'])
    ->condition('uid', $account->uid)
    ->condition('vid', $account->vid, $earlier ? '<' : '>')
    ->orderBy('vid', 'DESC')
    ->execute();

  foreach ($result->fetchCol() as $vid) {
    $revisions[] = user_revision_load($account->uid, $vid);
  }

  return $revisions;
}

/**
 * Form constructor for the profile filters form.
 */
function pw_profiles_filters_form($form, &$form_state, $parliament, $facets, $additional_filters_enabled = TRUE) {

  $constituency_values = _pw_profiles_facet_values($facets['field_user_constituency']);
  $party_values = _pw_profiles_facet_values($facets['field_user_party']);
  $list_values = _pw_profiles_facet_values($facets['field_user_list']);
  $list_position_values = _pw_profiles_facet_values($facets['field_user_list_position']);
  $gender_options = array_combine(_pw_profiles_facet_values($facets['field_user_gender']), array_map('t', _pw_profiles_facet_values($facets['field_user_gender'])));

  $parameters = drupal_get_query_parameters();

  if (strpos($parliament->name, 'EU') === 0) {
    $keys_placeholder = t('Enter a locality or name');
  }
  else {
    $keys_placeholder = t('Enter a postal code, locality or name');
  }

  $form['#method'] = 'get';
  $form['#action'] = url(current_path());
  $form['#attributes']['data-ajax-target'] = '#ajax';
  $form['#theme'] = 'filterbar';
  $form['keys'] = [
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#title_display' => 'invisible',
    '#default_value' => isset($parameters['keys']) ? $parameters['keys'] : '',
    '#attributes' => ['placeholder' => $keys_placeholder],
  ];

  if (strpos($parliament->name, 'Bayern') === 0) {
    $constituency_title = t('Constituency', [], ['context' => 'Bayern']);
    $list_title = t('List', [], ['context' => 'Bayern']);
    $list_position_title = t('List position', [], ['context' => 'Bayern']);
  }
  else {
    $constituency_title = t('Constituency', [], ['context' => '']);
    $list_title = t('List', [], ['context' => '']);
    $list_position_title = t('List position', [], ['context' => '']);
  }

  if (count($constituency_values) > 1) {
    $form['constituency'] = array(
      '#type' => 'select',
      '#title' => $constituency_title,
      '#title_display' => 'invisible',
      '#options' => ['' => t('All')] + _pw_profiles_options($constituency_values),
      '#default_value' => empty($parameters['constituency']) ? '' : $parameters['constituency'],
    );
  }
  if ($additional_filters_enabled) {
    if (count($list_values) > 1 && !pw_profiles_filter_disabled('field_user_list_tid', $parliament)) {
      $form['list'] = array(
        '#type' => 'radios',
        '#title' => $list_title,
        '#title_display' => 'invisible',
        '#options' => ['' => t('All')] + _pw_profiles_options($list_values),
        '#default_value' => empty($parameters['list']) ? '' : $parameters['list'],
        '#dropdown' => TRUE,
      );
    }
    if (count($list_position_values) > 1 && !pw_profiles_filter_disabled('field_user_list_position_tid', $parliament)) {
      $form['list_position'] = array(
        '#type' => 'select',
        '#title' => t('List position'),
        '#title_display' => 'invisible',
        '#options' => ['' => t('All')] + _pw_profiles_options($list_position_values),
        '#default_value' => empty($parameters['list_position']) ? '' : $parameters['list_position'],
        '#dropdown' => TRUE,
      );
    }
    if (count($party_values) > 1) {
      $form['party'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Filter by party'),
        '#title_display' => 'invisible',
        '#options' => _pw_profiles_options($party_values),
        '#multiple' => TRUE,
        '#default_value' => empty($parameters['party']) ? [] : $parameters['party'],
        '#dropdown' => TRUE,
      );
    }
    if (count($gender_options) > 1) {
      $form['gender'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Gender'),
        '#title_display' => 'invisible',
        '#options' => $gender_options,
        '#default_value' => empty($parameters['gender']) ? [] : $parameters['gender'],
        '#dropdown' => FALSE,
      );
    }
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Filter profiles'),
  );

  return $form;
}

/**
 * Form constructor for the street form.
 */
function pw_profiles_street_form($form, &$form_state, $parliament, $parameters) {
  $form['#method'] = 'get';
  $form['#action'] = url(current_path());

  $form['description'] = [
    '#markup' => '<p>' . t('Please select a street address to find your constituency.') . '</p>',
  ];

  $attributes = [
    'data-ajax--url' => url("profiles/$parliament->tid/${parameters['keys']}/street-search"),
    'data-placeholder' => t('Please enter your street name'),
  ];
  $form['constituency'] = [
    '#type' => 'select',
    '#options' =>  [],
    '#attributes' => $attributes,
    '#default_value' => '0',
  ];

  $form['submit'] = [
    '#type' => 'submit',
    '#value' => t('To constituency', [], ['context' => 'Bayern']),
  ];

  return $form;
}

/**
 * Returns TRUE if the filter is disabled for the parliament, FALSE otherwise.
 *
 * @param string $filter
 *
 * @param object $parliament
 *
 * @return bool
 */
function pw_profiles_filter_disabled($filter, $parliament) {
  $items = field_get_items('taxonomy_term', $parliament, 'field_parliament_filter_disabled');

  if (is_array($items)) {
    foreach ($items as $item) {
      if ($item['value'] == $filter) {
        return TRUE;
      }
    }
  }

  return FALSE;
}

/**
 * Returns the account object identified by the given name.
 *
 * @param string $name
 *   The username.
 *
 * @return object
 *   An account object with the given name.
 */
function pw_profiles_username_load($name) {
  return user_load_by_name($name);
}

/**
 * Returns a query object for fetching politicians.
 *
 * @param type $parliament_term
 *   The parliament term.
 * @param type $role_name
 *   The role (candidates or deputies).
 *
 * @return SearchApiQuery
 *   The search query object.
 */
function pw_profiles_base_search_query($parliament_term, $role_name) {
  $q = search_api_query('politician_archive_index', ['search_api_facets' => _pw_profiles_facets()]);
  $q->condition('field_user_retired', NULL, '=');
  $q->condition('field_user_parliament', $parliament_term->tid);

  if ($role_name == 'deputies') {
    $q->condition('field_user_roles_for_view_mode_s', PW_GLOBALS_DEPUTY_TID);
  }
  else {
    $q->condition('field_user_roles_for_view_mode_s', PW_GLOBALS_CANDIDATE_TID);
  }
  return $q;
}

/**
 * Returns list of facets for the profile page.
 *
 * @return array
 *   An associative array to be used as facets option for a query.
 */
function _pw_profiles_facets() {
  $common = ['limit' => -1, 'min_count' => 1, 'missing' => TRUE, 'operator' => 'or'];
  return [
    'field_user_list' => ['field' => 'field_user_list'] + $common,
    'field_user_list_position' => ['field' => 'field_user_list_position'] + $common,
    'field_user_gender' => ['field' => 'field_user_gender'] + $common,
    'field_user_party' => ['field' => 'field_user_party'] + $common,
    'field_user_constituency' => ['field' => 'field_user_constituency'] + $common,
  ];
}

/**
 * Extracts the values from a facet.
 *
 * This function also removes the additional double quotes around the value.
 *
 * @param array $facet
 *   The facet.
 *
 * @return array
 *   An array of values for filtering the result.
 */
function _pw_profiles_facet_values($facet) {
  $values = [];

  if (is_array($facet)) {
    foreach ($facet as $result) {
      if ($result['filter'] != '!') {
        $values[] = trim($result['filter'], '"');
      }
    }
  }

  return $values;
}

/**
 * Returns taxonomy term options for the given term IDs.
 *
 * @param array $values
 *   An array of taxonomy term IDs
 *
 * @return array
 *   An array of taxonomy term names keyed by term ID.
 */
function _pw_profiles_options(array $values) {
  static $terms = [];

  if (empty($terms)) {
    $terms = db_select('taxonomy_term_data', 't')
      ->fields('t', array('tid', 'name'))
      ->condition('vid', array(17, 19, 32, 38, 39), 'IN')
      ->execute()
      ->fetchAllKeyed();
    natsort($terms);
  }

  return array_intersect_key($terms, array_flip($values));
}

/**
 * Returns constituency descriptors grouped by constituency.
 *
 * @param array $constituency_values
 *   An array of constituency term IDs.
 * @param string $url
 *   The URL.
 * @param array $parameters
 *   The query parameters.
 *
 * @return
 *   An array of constituency descriptors keyed by term ID.
 */
function _pw_profiles_constituency_selection_items(array $constituency_values, $url, $parameters) {
  $items = [];

  foreach (taxonomy_term_load_multiple($constituency_values) as $term) {
    $parameters['constituency'] = $term->tid;
    $descriptor_items = field_get_items('taxonomy_term', $term, 'field_constituency_ac_descriptor');
    if (!$descriptor_items) {
      $items[] = ['data' => $term->name, 'href' => url($url, ['query' => $parameters])];
    }
    else {
      foreach (explode(',', rtrim($descriptor_items[0]['safe_value'], ',')) as $descriptor) {
        list($postal_code, $locality) = explode(':', $descriptor);
        if ($postal_code == $parameters['keys']) {
          $items[] = ['data' => $locality, 'href' => url($url, ['query' => $parameters])];
        }
      }
    }
  }

  return $items;
}

/**
 * Returns an associative array to be used as options for a select box.
 *
 * @param object $account
 *   The account object.
 *
 * @return array
 *   An array with URLs as keys and labels for the legislative terms as values.
 */
function _pw_profiles_revision_dropdown($account) {
  $items = [];

  $revisions = array_merge([$account], pw_profiles_archived_revisions($account, FALSE), [$account], pw_profiles_archived_revisions($account, TRUE));

  foreach ($revisions as $revision) {
    if (in_array(PW_GLOBALS_DEPUTY_RID, array_keys($revision->roles))) {
      $text = pw_profiles_parliament($revision)->name;
    }
    else {
      $text = preg_replace('/\-\d+\s*$/', '', pw_profiles_parliament($revision)->name) . ' (Wahlen)';
    }
    $items[] = ['path' => url(entity_uri('user', $revision)['path']), 'title' => $text];
  }
  return $items;
}

/**
 * Returns whether the given search is exclusively for a postal code.
 *
 * @param array $parameters
 *   The query parameters
 *
 * @return bool
 *   TRUE if $parameters['keys'] matches the postal code pattern and there
 *   are no other search parameters, FALSE otherwise.
 */
function _pw_profiles_is_postal_code_search($parameters) {
  if (!isset($parameters['keys'])) {
    return FALSE;
  }
  if (count(array_filter($parameters)) > 1) {
    return FALSE;
  }
  return preg_match('/^[0-9]{4,5}$/', trim($parameters['keys']));
}

/**
 * Returns whether the given search requires the user to select a street.
 *
 * @param object $parliament
 *   The parliament_term.
 * @param array $parameters
 *   The query parameters.
 *
 * @return bool
 *   TRUE if $parameters['keys'] is a postal code from Munich or Nuremberg
 */
function _pw_profiles_street_required($parameters, $parliament) {
  $parliament_has_street_search = in_array($parliament->tid, variable_get('pw_profiles_parliaments_with_street_search', []));
  $postal_codes_mn = variable_get('pw_profiles_postal_codes_mn', []);
  return $parliament_has_street_search && in_array(trim($parameters['keys']), $postal_codes_mn);
}

/**
 * Returns HTML for a summary of the search result.
 *
 * @param array $variables
 *   An associative array containing:
 *   - response
 *   - role_name
 *   - filters
 */
function theme_profile_search_summary($variables) {
  $output = '';
  $facets = $variables['response']['search_api_facets'];
  $link_options = ['attributes' => ['data-ajax-target' => '#ajax']];

  $options['@count'] = $variables['response']['result count'];
  $options['@data-ajax-target'] = $link_options['attributes']['data-ajax-target'];

  if (!empty($variables['filters']['party'])) {
    $parties_count = count($variables['filters']['party']);
    $parties_text = format_plural($parties_count, '1 party', '@count parties');
    $options['!parties'] = l($parties_text, current_path(), $link_options + ['query' => _pw_profiles_reject_filter($variables['filters'], 'party')]);
  }
  else {
    $parties_count = count(_pw_profiles_facet_values($facets['field_user_party']));
    $parties_text = format_plural($parties_count, '1 party', '@count parties');
    $options['!parties'] = $parties_text;
  }

  if (!empty($variables['filters']['constituency'])) {
    $constituencies_count = 1;
    $constituencies_text = format_plural($constituencies_count, '1 constituency', '@count constituencies');
    $options['!constituencies'] = l($constituencies_text, current_path(), $link_options + ['query' => _pw_profiles_reject_filter($variables['filters'], 'constituency')]);
  }
  else {
    $constituencies_count = count(_pw_profiles_facet_values($facets['field_user_constituency']));
    $constituencies_text = format_plural($constituencies_count, '1 constituency', '@count constituencies');
    $options['!constituencies'] = $constituencies_text;
  }

  $output .= '<p>';

  if (empty($variables['filters']['gender'])) {
    if ($variables['role_name'] == 'candidates') {
      $output .= format_plural($variables['response']['result count'], 'Found 1 candidate from !parties and !constituencies', 'Found @count candidates from !parties and !constituencies', $options);
    }
    else {
      $output .= format_plural($variables['response']['result count'], 'Found 1 deputy from !parties and !constituencies', 'Found @count deputies from !parties and !constituencies', $options);
    }
  }
  elseif ($variables['filters']['gender'] == ['male' => 'male', 'female' => 'female']) {
    $options['@url'] = url(current_path(), ['query' => _pw_profiles_reject_filter($variables['filters'], 'gender')]);
    if ($variables['role_name'] == 'candidates') {
      $output .= format_plural($variables['response']['result count'], 'Found @count <a href="@url" data-ajax-target="@data-ajax-target">female or male</a> candidate from !parties and !constituencies', 'Found @count <a href="@url" data-ajax-target="@data-ajax-target">female and male</a> candidates from !parties and !constituencies', $options);
    }
    else {
      $output .= format_plural($variables['response']['result count'], 'Found @count <a href="@url" data-ajax-target="@data-ajax-target">female or male</a> deputy from !parties and !constituencies', 'Found @count <a href="@url" data-ajax-target="@data-ajax-target">female and male</a> deputies from !parties and !constituencies', $options);
    }
  }
  elseif (!empty($variables['filters']['gender']['male'])) {
    $options['@url'] = url(current_path(), ['query' => _pw_profiles_reject_filter($variables['filters'], 'gender')]);
    if ($variables['role_name'] == 'candidates') {
      $output .= format_plural($variables['response']['result count'], 'Found 1 <a href="@url" data-ajax-target="@data-ajax-target">male</a> candidate from !parties and !constituencies', 'Found @count <a href="@url" data-ajax-target="@data-ajax-target">male</a> candidates from !parties and !constituencies', $options);
    }
    else {
      $output .= format_plural($variables['response']['result count'], 'Found 1 <a href="@url" data-ajax-target="@data-ajax-target">male</a> deputy from !parties and !constituencies', 'Found @count <a href="@url" data-ajax-target="@data-ajax-target">male</a> deputies from !parties and !constituencies', $options);
    }
  }
  elseif (!empty($variables['filters']['gender']['female'])) {
    $options['@url'] = url(current_path(), ['query' => _pw_profiles_reject_filter($variables['filters'], 'gender')]);
    if ($variables['role_name'] == 'candidates') {
      $output .= format_plural($variables['response']['result count'], 'Found 1 <a href="@url" data-ajax-target="@data-ajax-target">female</a> candidate from !parties and !constituencies', 'Found @count <a href="@url" data-ajax-target="@data-ajax-target">female</a> candidates from !parties and !constituencies', $options);
    }
    else {
      $output .= format_plural($variables['response']['result count'], 'Found 1 <a href="@url" data-ajax-target="@data-ajax-target">female</a> deputy from !parties and !constituencies', 'Found @count <a href="@url" data-ajax-target="@data-ajax-target">female</a> deputies from !parties and !constituencies', $options);
    }
  }

  if (!empty($variables['filters']['list'])) {
    $list = taxonomy_term_load($variables['filters']['list']);
  }

  if (!empty($variables['filters']['list_position'])) {
    $list_position = taxonomy_term_load($variables['filters']['list_position']);
  }

  if (isset($list) && isset($list_position)) {
    $list_link = l($list->name, current_path(), $link_options + ['query' => _pw_profiles_reject_filter($variables['filters'], 'list')]);
    $position_text = t('list position @position', ['@position' => $list_position->name]);
    $position_link = l($position_text, current_path(), $link_options + ['query' => _pw_profiles_reject_filter($variables['filters'], 'list_position')]);
    $output .= t(' having !position of !list', ['!position' => $position_link, '!list' => $list_link]);
  }
  elseif (isset($list)) {
    $list_link = l($list->name, current_path(), $link_options + ['query' => _pw_profiles_reject_filter($variables['filters'], 'list')]);
    $output .= t(' of !list', ['!list' => $list_link]);
  }
  elseif (isset($list_position)) {
    $position_text = t('list position @position', ['@position' => $list_position->name]);
    $position_link = l($position_text, current_path(), $link_options + ['query' => _pw_profiles_reject_filter($variables['filters'], 'list_position')]);
    $output .= t(' having !position', ['!position' => $position_link]);
  }

  if (!empty($variables['filters']['keys'])) {
    $options['!keys'] = l(check_plain($variables['filters']['keys']), current_path(), $link_options + ['query' => _pw_profiles_reject_filter($variables['filters'], 'keys')]);
    $output .= t(', matching: !keys', $options);
  }

  if (!empty(array_filter($variables['filters']))) {
    $output .= ' ' . l(t('Reset all filters'), current_path(), $link_options);
  }

  $output .= '</p>';

  return $output;
}

/**
 * Removes the filter with the given key.
 *
 * @param array $filters
 *   The filters.
 * @param string $key
 *
 * @return array
 *   The filters without the given key.
 */
function _pw_profiles_reject_filter(array $filters, $key, $value = NULL) {
  if (array_key_exists($key, $filters)) {
    if (!isset($value)) {
      unset($filters[$key]);
    }
    else {
      unset($filters[$key][array_search($value, $filters[$key])]);
    }
  }
  return array_filter($filters);
}

/**
 * Returns options eligible for the given user account.
 *
 * @param array $options
 *   The options.
 * @param $account
 *   The account object.
 *
 * @return array
 *   The eligible options.
 */
function _pw_profiles_filter_options(array $options, $account) {
  $eligible_terms = ['_none' => NULL];
  $parliament = pw_profiles_parliament($account);

  if (isset($parliament)) {
    $q = new EntityFieldQuery();
    $q->entityCondition('entity_type', 'taxonomy_term')
      ->fieldCondition('field_parliament', 'tid', $parliament->tid);
    $result = $q->execute();
    if (isset($result['taxonomy_term'])) {
      $eligible_terms += $result['taxonomy_term'];
    }
  }

  return array_intersect_key($options, $eligible_terms);
}

t('Constituency result', [], ['context' => '']);
t('Constituency result', [], ['context' => 'Bayern']);
t('@result % (via constituency)', ['@result' => 0], ['context' => '']);
t('@result % (via constituency)', ['@result' => 0], ['context' => 'Bayern']);
t('@result % (via list)', ['@result' => 0], ['context' => '']);
t('@result % (via list)', ['@result' => 0], ['context' => 'Baden-Württemberg']);
t('@result % (via list)', ['@result' => 0], ['context' => 'Bayern']);
