<?php
/**
 * @file
 * Code for the PW Parliaments feature.
 */

include_once 'pw_parliaments.features.inc';

/**
 * Implements hook_taxonomy_term_presave().
 */
function pw_parliaments_taxonomy_term_presave($term) {
  // check if is parliaments vocabulary
  if($term->vid == 18 && module_exists('pw_userarchives')){
    db_delete('user_archive_cache')
      ->condition('parliament_name', $term->original->name)
      ->execute();
  }
}

/**
 * Implements hook_taxonomy_term_update().
 */
function pw_parliaments_taxonomy_term_update($term) {
  // check if is parliaments vocabulary
  if($term->vid == 18 && module_exists('pw_userarchives')){
    pw_userarchives_cron();
    if(module_exists('pw_cache')){
      $query = db_select('user_archive_cache', 'uac')
        ->fields('uac', array('user_name', 'vid', 'actual_profile'))
        ->condition('parliament_name', $term->name);
      $result = $query->execute();
      if($result->rowCount() > 0){
        while($row = $result->fetchAssoc()){
          if($row['actual_profile'] == 1){
            $expire_paths[] = 'profile/'.$row['user_name'];
          }
          else{
            $expire_paths[] = 'profile/'.$row['user_name'].'/archive/'.$row['vid'];
          }
        }
        pw_cache_expire_cache($expire_paths);
      }
    }
  }
}

/**
 * Implements hook_taxonomy_term_view_alter().
 */
function pw_parliaments_menu_alter(&$items) {
  $items['taxonomy/term/%taxonomy_term']['page callback'] = 'pw_parliaments_taxonomy_term_page';
  unset($items['taxonomy/term/%taxonomy_term_load']['file']);
}

/**
 * Displays parliament pages, leaving other term pages to the default callback.
 */
function pw_parliaments_taxonomy_term_page($term) {
  if ($term->vid == 18) {
    if (empty($term->description)) {
      return '';
    }
    else {
      return [
        '#prefix' => '<div class="container">',
        '#markup' => $term->description,
        '#suffix' => '</div>',
      ];
    }
  }
  else {
    module_load_include('inc', 'taxonomy', 'taxonomy.pages');
    return taxonomy_term_page($term);
  }
}
