<?php
/**
 * @file
 * Code for the PW Parliaments feature.
 */

include_once 'pw_parliaments.features.inc';

/**
 * Implements hook_taxonomy_term_presave().
 */
function pw_parliaments_taxonomy_term_presave($term) {
  // check if is parliaments vocabulary
  if($term->vid == 18 && module_exists('pw_userarchives')){
    db_delete('user_archive_cache')
      ->condition('parliament_name', $term->original->name)
      ->execute();
  }
}

/**
 * Implements hook_taxonomy_term_update().
 */
function pw_parliaments_taxonomy_term_update($term) {
  // check if is parliaments vocabulary
  if($term->vid == 18 && module_exists('pw_userarchives')){
    pw_userarchives_cron();
    if(module_exists('pw_cache')){
      $query = db_select('user_archive_cache', 'uac')
        ->fields('uac', array('user_name', 'vid', 'actual_profile'))
        ->condition('parliament_name', $term->name);
      $result = $query->execute();
      if($result->rowCount() > 0){
        while($row = $result->fetchAssoc()){
          if($row['actual_profile'] == 1){
            $expire_paths[] = 'profile/'.$row['user_name'];
          }
          else{
            $expire_paths[] = 'profile/'.$row['user_name'].'/archive/'.$row['vid'];
          }
        }
        pw_cache_expire_cache($expire_paths);
      }
    }
  }
}

/**
 * Implements hook_taxonomy_term_view_alter().
 */
function pw_parliaments_menu_alter(&$items) {
  $items['taxonomy/term/%taxonomy_term']['page callback'] = 'pw_parliaments_taxonomy_term_page';
  unset($items['taxonomy/term/%taxonomy_term_load']['file']);
}

/**
 * Implements hook_block_list_alter().
 *
 * Removes title block from taxonomy term pages of funded parliaments.
 */
function pw_parliaments_block_list_alter(&$blocks) {
  $term = menu_get_object('taxonomy_term', 2);

  if (!isset($term) || !pw_parliaments_is_funded($term)) {
    return;
  }

  foreach ($blocks as $key => $block) {
    if ($block->module == 'pw_globals' && $block->delta == 'title') {
      unset($blocks[$key]);
    }
  }
}

/**
 * Displays parliament pages, leaving other term pages to the default callback.
 */
function pw_parliaments_taxonomy_term_page($term) {
  if ($term->vocabulary_machine_name == 'parliaments') {
    if (pw_parliaments_is_funded($term)) {
      return '';
    }
    else {
      return taxonomy_term_view($term);
    }
  }

  $build = taxonomy_term_view($term);
  $nids = taxonomy_select_nodes($term->tid, TRUE, variable_get('default_nodes_main', 12));

  if ($nids) {
    $nodes = node_load_multiple($nids);
    $build = node_view_multiple($nodes, 'tile');
    $build['#theme_wrappers'] = ['container__tiles'];
    $build['pager'] = [
      '#theme' => 'pager',
      '#weight' => 5,
    ];
  }
  else {
    $build['no_content'] = [
      '#prefix' => '<p>',
      '#markup' => t('There is currently no content classified with this term.'),
      '#suffix' => '</p>',
    ];
  }

  return $build;
}

/**
 * Returns TRUE if the given parliament is funded, FALSE otherwise.
 *
 * If the given term is not a parliament term returns NULL.
 *
 * @param object $term
 *   The parliament term.
 *
 * @return bool
 *   TRUE if the given parliament is funded, FALSE otherwise
 */
function pw_parliaments_is_funded($term) {
  if ($term->vocabulary_machine_name != 'parliaments') {
    return NULL;
  }
  elseif (empty($term->description)) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}
